import { chromium } from '@playwright/test';
import { homedir } from 'node:os';
import { join } from 'node:path';

const browser = await chromium.launch({ headless: true, executablePath: join(homedir(), 'AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe') });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
page.on('framenavigated', f => console.log('navigation', f.url()));
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
const snap = async name => {
  await page.screenshot({ path: `workbench/${name}.png` });
  console.log(`\n${name}\n`, (await page.locator('body').innerText()).slice(0, 7000));
};
await snap('ux-01-menu');
await page.getByRole('button', { name: 'Обучение · 5 минут' }).click();
await snap('ux-02-tutorial-start');
console.log('buttons', await page.locator('button').allTextContents());
console.log('units', await page.locator('[data-unit]').evaluateAll(els => els.map(e => ({ id: e.getAttribute('data-unit'), tag: e.tagName, box: e.getBoundingClientRect().toJSON() }))));
await page.locator('[data-unit="blue-1"]').click();
await page.waitForFunction(() => document.body.innerText.length > 50, null, { timeout: 5000 }).catch(() => {});
console.log('after select url', page.url());
await snap('ux-03-selected');
console.log('board', (await page.locator('#board').evaluate(e => e.outerHTML)).slice(0, 3000));
await page.mouse.move(720, 390);
await page.waitForTimeout(250);
await snap('ux-04-hover-move');
await page.mouse.click(720, 390);
await page.waitForTimeout(500);
await snap('ux-05-after-move');
for (const [x,y] of [[720,335],[770,360],[620,390],[620,335],[720,285],[770,310],[570,420],[820,385]]) {
  await page.mouse.move(x,y);
  await page.waitForTimeout(80);
  const t=await page.locator('body').innerText();
  console.log('hover',x,y,t.match(/ТОЧНЫЙ ПРОГНОЗ ДО ПОДТВЕРЖДЕНИЯ\n([^]*?)\nХРОНИКА/)?.[1]);
}
await page.mouse.click(770,360);
await page.waitForTimeout(400);
await snap('ux-06-position');
await page.mouse.move(920,405);
await page.waitForTimeout(150);
await snap('ux-07-hover-enemy');
await page.locator('[data-unit="blue-2"]').click();
await page.waitForTimeout(200);
await page.mouse.move(820, 490);
await page.waitForTimeout(150);
await snap('ux-08-archer-hover');
await page.mouse.click(820,490);
await page.waitForTimeout(350);
await snap('ux-09-attack');
await page.getByRole('button', { name: 'Завершить ход ↵' }).click();
await page.waitForTimeout(1800);
await snap('ux-10-next-turn');
await page.getByRole('button', { name: 'Ⅱ' }).click();
await page.waitForTimeout(150);
await snap('ux-11-pause');
console.log('pause buttons', await page.locator('button').allTextContents());
await browser.close();
console.log('errors', errors);
