import {chromium} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {homedir} from 'node:os';
import {registerHooks} from 'node:module';
import assert from 'node:assert/strict';
registerHooks({resolve(s,c,next){if(s.startsWith('.')&&!/\.[cm]?[jt]s$/.test(s)){try{return next(s+'.ts',c)}catch{}try{return next(s+'/index.ts',c)}catch{}}return next(s,c)}});
const {createGame,legalMoves,getUnitRules}=await import('../src/engine/index.ts');
let browser;try{browser=await chromium.launch({headless:true})}catch{browser=await chromium.launch({headless:true,executablePath:join(homedir(),'AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe')})}
const out='workbench/recheck-shots';await mkdir(out,{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:900}}),record={artifact:await readFile('dist/index.html','utf8'),errors:[],checks:[],scenes:[]};
page.on('pageerror',e=>record.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')record.errors.push(m.text())});
await page.route('**/*',async r=>{const name=new URL(r.request().url()).pathname.slice(1)||'index.html';try{await r.fulfill({body:await readFile(resolve('dist',name)),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.svg')?'image/svg+xml':'text/html'})}catch{record.errors.push('missing '+name);await r.fulfill({status:404,body:'missing'})}});
await page.addInitScript(()=>localStorage.setItem('ab-volume','0'));
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ab-save')));
async function shot(n){await page.screenshot({path:`${out}/${n}.png`});record.scenes.push({name:n,text:await page.locator('body').innerText(),state:await saved(),layout:await page.evaluate(()=>Object.fromEntries(['objective-panel','preview-panel','selection-panel','units-panel'].map(id=>{const e=document.getElementById(id),b=e?.getBoundingClientRect();return[id,e?{display:getComputedStyle(e).display,rect:{x:b.x,y:b.y,width:b.width,height:b.height}}:null]})))})}
async function load(g){await page.evaluate(s=>localStorage.setItem('ab-save',JSON.stringify(s)),g);await page.reload();await page.locator('#continue').click();await page.waitForTimeout(350)}
const previous=process.argv.includes('--focused')?JSON.parse(await readFile(`${out}/results.json`,'utf8')):null;
const pvpPrevious=process.argv.includes('--pvp')?JSON.parse(await readFile(`${out}/results.json`,'utf8')):null;
async function check(name,fn){if(previous&&!/A6-|mason-|sapper-|A8-/.test(name)){record.checks.push(previous.checks.find(c=>c.name===name));record.scenes.push(...previous.scenes.filter(s=>!record.scenes.some(v=>v.name===s.name)));return}try{const detail=await fn();record.checks.push({name,passed:true,detail})}catch(e){record.checks.push({name,passed:false,error:e.stack});await shot('FAIL-'+name.replace(/[^a-z0-9]/gi,'-'))}}
async function aiDone(){await page.waitForFunction(()=>{const s=JSON.parse(localStorage.getItem('ab-save'));return s.team==='blue'||s.winner},{timeout:30000})}
async function hover(g,x,y){const b=await page.locator('#board').boundingBox(),w=g.map.width,h=g.map.height,width=page.viewportSize().width,compact=width<=1100,z=compact?(w>=16?(width<=650?.72:.9):width<=650?1.05:1.25):w>=16?1.14:w<=9?1.6:1.35,cy=compact?-35:w>=16?20:5,s=Math.min(62,Math.max(39,b.width/(w*1.7)))*z,t=g.map.tiles[y*w+x];const px=b.x+b.width/2+(x-y-(w-h)/2)*s*.5,py=b.y+b.height*.48+cy+(x+y-(w+h)/2)*s*.24-t.h*s*.21;for(const [dx,dy] of [[0,-.5],[0,-.6],[0,0],[-.38,0],[.38,0],[0,-.18],[0,.18]]){const p={x:px+dx*s,y:py+dy*s};await page.mouse.move(p.x,p.y);if(await page.evaluate(()=>document.querySelector('#help strong')?.textContent)===`${x+1}:${y+1}`)return p}throw Error(`Cannot hover ${x}:${y}`)}
async function select(id){if(page.viewportSize().width<=1100&&await page.locator('#inspect-toggle').getAttribute('aria-expanded')!=='true')await page.locator('#inspect-toggle').click();await page.locator(`[data-unit="${id}"]`).click();if(page.viewportSize().width<=1100)await page.locator('#inspect-toggle').click()}
function stage(variant){const g=createGame({map:'highland',mode:'pvp',objective:'elimination'});g.map.tiles.forEach(t=>{t.h=0;t.terrain='grass';delete t.object;delete t.hp});g.units.forEach(u=>u.alive=false);const engineer=g.units.find(u=>u.team==='blue'),ally=g.units.find(u=>u.id==='blue-2'),enemy=g.units.find(u=>u.team==='red');Object.assign(engineer,{alive:true,archetype:'engineer',variant,modifier:undefined,artifact:undefined,x:3,y:3,commander:false,moved:false,acted:false});engineer.hp=engineer.maxHp=getUnitRules(engineer).hp;Object.assign(ally,{alive:true,x:4,y:3,commander:false});Object.assign(enemy,{alive:true,x:7,y:7,commander:false});return{g,engineer,ally}}
try{
await page.goto('http://game.test/');
if(pvpPrevious){
record.checks.push(...pvpPrevious.checks.filter(c=>c.name!=='local-pvp-red-input-gate'));record.scenes.push(...pvpPrevious.scenes.filter(c=>!c.name.startsWith('19-pvp')&&!c.name.startsWith('20-pvp')));
await check('local-pvp-red-input-gate',async()=>{await page.locator('#hotseat').click();await page.locator('#start').click();await page.locator('#start').click();assert.equal((await saved()).mode,'pvp');await page.keyboard.press('Enter');let g=await saved();assert.equal(g.team,'red');assert.equal(await page.locator('#end-turn').isEnabled(),true);const u=g.units.find(u=>u.alive&&u.team==='red'),m=legalMoves(g,u.id).find(m=>m.x!==u.x||m.y!==u.y);assert(m);await select(u.id);const pos=await hover(g,m.x,m.y);await shot('19-pvp-red-move-preview');await page.mouse.click(pos.x,pos.y);await page.waitForTimeout(500);g=await saved();assert.equal(g.history.at(-1).type,'move');assert.equal(g.history.at(-1).unitId,u.id);assert.equal(g.units.find(v=>v.id===u.id).x,m.x);assert.equal(g.units.find(v=>v.id===u.id).y,m.y);assert.equal(await page.locator('#end-turn').isEnabled(),true);await page.keyboard.press('Enter');g=await saved();assert.equal(g.team,'blue');assert.equal(g.turn,2);await shot('20-pvp-blue-round-two');return{mode:g.mode,team:g.team,turn:g.turn,history:g.history,movedUnit:g.units.find(v=>v.id===u.id)}});
}else{
await check('A1-ai-enter-gate',async()=>{await load(createGame({map:'highland',mode:'ai',objective:'control'}));await page.keyboard.press('Enter');assert.equal(await page.locator('#end-turn').isDisabled(),true);await page.keyboard.press('Enter');assert.equal((await saved()).team,'red');await shot('01-ai-enter-ignored');await aiDone();const g=await saved();assert(g.history.filter(c=>c.type!=='endTurn').length>1);await shot('02-ai-finished');return{history:g.history}});
await check('A2-pause-before-ai-resume',async()=>{await load(createGame({map:'watch',mode:'ai',mission:'watch'}));await page.keyboard.press('Enter');await page.keyboard.press('Escape');const before=await saved();await page.waitForTimeout(800);assert.deepEqual(await saved(),before);await shot('03-paused-before-ai');await page.keyboard.press('Escape');await aiDone();await shot('04-resumed-before-ai');return{beforeHistory:before.history,afterHistory:(await saved()).history}});
await check('A3-mid-ai-pause-resume',async()=>{await load(createGame({map:'highland',mode:'ai',objective:'control'}));await page.keyboard.press('Enter');await page.waitForTimeout(300);await page.keyboard.press('Escape');const before=await saved();assert(before.history.length>1);await page.waitForTimeout(1500);assert.deepEqual(await saved(),before);await shot('05-mid-ai-frozen');await page.keyboard.press('Escape');await aiDone();await shot('06-mid-ai-resumed');return{beforeHistory:before.history,afterHistory:(await saved()).history}});
await check('A3-menu-stops-worker',async()=>{await load(createGame({map:'highland',mode:'ai',objective:'control'}));await page.keyboard.press('Enter');await page.waitForTimeout(300);await page.keyboard.press('Escape');await page.locator('[data-modal="menu"]').click();const before=await saved();await page.waitForTimeout(2500);assert.deepEqual(await saved(),before);assert.equal(await page.locator('#board').count(),0);assert.equal(await page.locator('#campaign').count(),1);await shot('07-menu-stable');return{history:before.history}});
await check('restart-cancels-worker',async()=>{await load(createGame({map:'highland',mode:'ai',objective:'control'}));await page.keyboard.press('Enter');await page.waitForTimeout(300);await page.keyboard.press('Escape');await page.locator('[data-modal="restart"]').click();const fresh=await saved();assert.equal(fresh.team,'blue');assert.equal(fresh.history.length,0);await page.waitForTimeout(2500);assert.deepEqual(await saved(),fresh);await shot('08-restart-stable')});
await check('A6-next-briefing-A7-watch-selected-sword',async()=>{const g=createGame({map:'ford',mode:'ai',mission:'ford'}),u=g.units.find(v=>v.team==='blue'),enemy=g.units.find(v=>v.team==='red');u.x=4;u.y=3;enemy.hp=1;await load(g);await select(u.id);const p=await hover(g,enemy.x,enemy.y);await page.mouse.click(p.x,p.y);await page.locator('[data-modal="campaign-next"]').waitFor();await page.locator('[data-modal="campaign-next"]').click();assert.equal(await page.locator('#board').count(),0);assert.equal(await page.locator('#campaign-start').getAttribute('data-id'),'watch');await shot('09-next-briefing');await page.locator('#campaign-start').click();assert.match(await page.locator('#selection-panel').innerText(),/Мечник/);await shot('10-watch-sword-selected')});
for(const width of [1024,640])await check('A4-A5-compact-'+width,async()=>{await page.setViewportSize({width,height:width===640?800:768});await load(createGame({map:'highland',mode:'ai',objective:'control'}));const g=await saved();const hoverable=[];for(const u of g.units.filter(u=>u.alive)){await hover(g,u.x,u.y);hoverable.push(u.id)};for(const id of ['objective-panel','preview-panel'])assert.equal(await page.locator('#'+id).isVisible(),true);await shot(`11-compact-${width}-all-units`);await page.locator('#inspect-toggle').click();assert.equal(await page.locator('#selection-panel').isVisible(),true);await page.locator('[data-unit="blue-1"]').click();assert.equal(await page.locator('[data-action="ability"]').isVisible(),true);await page.locator('[data-action="ability"]').click();await shot(`12-compact-${width}-inspector`);await page.locator('#inspect-toggle').click();await page.keyboard.press('Tab');assert.equal(await page.locator('#inspect-toggle').getAttribute('aria-expanded'),'false');return{hoverable}});
await page.setViewportSize({width:1440,height:900});
await check('mason-friendly-occupied-bridge',async()=>{const {g,engineer,ally}=stage('mason');Object.assign(g.map.tiles[ally.y*g.map.width+ally.x],{terrain:'bridge',object:'fragile',hp:2});await load(g);await select(engineer.id);await page.locator('[data-action="ability"]').click();const p=await hover(g,ally.x,ally.y);assert.match(await page.locator('#preview-panel').innerText(),/укреплён.*4 прочности/);await shot('13-mason-preview');await page.mouse.click(p.x,p.y);const after=await saved();assert.equal(after.map.tiles[ally.y*g.map.width+ally.x].hp,4);assert.equal(after.units.find(u=>u.id===ally.id).hp,ally.hp);assert.equal(after.history.at(-1).unitId,engineer.id);await shot('14-mason-strengthened')});
await check('sapper-trap-three-damage-hover',async()=>{let {g,engineer,ally}=stage('sapper');ally.x=4;ally.y=4;await load(g);await select(engineer.id);await page.locator('[data-action="ability"]').click();const p=await hover(g,4,3);assert.match(await page.locator('#preview-panel').innerText(),/3 урона/);await shot('15-sapper-placement-preview');await page.mouse.click(p.x,p.y);g=await saved();assert.equal(g.map.tiles[3*g.map.width+4].trapDamage,3);await select(ally.id);const target=await hover(g,4,3);assert.match(await page.locator('#help').innerText(),/ловушка.*3 урона/i);assert.match(await page.locator('#preview-panel').innerText(),/Опасность 3/);await shot('16-sapper-trigger-preview');await page.mouse.click(target.x,target.y);assert.equal((await saved()).units.find(u=>u.id===ally.id).hp,ally.hp-3);await shot('17-sapper-triggered')});
await check('A8-aimed-shot-specific-reason',async()=>{await load(createGame({map:'watch',mode:'ai',mission:'watch'}));let g=await saved();const archer=g.units.find(u=>u.team==='blue'&&u.archetype==='archer'),enemy=g.units.find(u=>u.team==='red');await select(archer.id);await page.keyboard.press('2');const p=await hover(g,enemy.x,enemy.y);await page.mouse.click(p.x,p.y);g=await saved();await hover(g,2,3);await shot('18-aimed-shot-reason');const preview=await page.locator('#preview-panel').innerText();assert.match(preview,/После прицельного выстрела движение недоступно/);return{preview}});
}
}finally{record.passed=record.checks.every(c=>c.passed)&&record.errors.length===0;await writeFile(`${out}/results.json`,JSON.stringify(record,null,2));await browser.close()}
console.log(JSON.stringify({passed:record.passed,errors:record.errors,checks:record.checks}));

