import {chromium} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {homedir} from 'node:os';
import {registerHooks} from 'node:module';
import assert from 'node:assert/strict';
registerHooks({resolve(s,c,next){if(s.startsWith('.')&&!/\.[cm]?[jt]s$/.test(s)){try{return next(s+'.ts',c)}catch{}try{return next(s+'/index.ts',c)}catch{}}return next(s,c)}});
const {createGame,previewAction,legalMoves,applyAction}=await import('../src/engine/index.ts');
let browser;try{browser=await chromium.launch({headless:true})}catch{browser=await chromium.launch({headless:true,executablePath:join(homedir(),'AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe')})}
const out='workbench/howto-shots';await mkdir(out,{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:900}}),record={artifact:await readFile('dist/index.html','utf8'),errors:[],checks:[],scenes:[]};
page.on('pageerror',e=>record.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')record.errors.push(m.text())});
await page.route('**/*',async r=>{const name=new URL(r.request().url()).pathname.slice(1)||'index.html';try{await r.fulfill({body:await readFile(resolve('dist',name)),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.svg')?'image/svg+xml':'text/html'})}catch{record.errors.push('missing '+name);await r.fulfill({status:404,body:'missing'})}});
await page.addInitScript(()=>localStorage.setItem('ab-volume','0'));
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ab-save')));
async function shot(n){if(n.includes('-colors'))await page.waitForFunction(()=>{const b=document.querySelector('#guide-colors')?.getBoundingClientRect();return b&&b.top>=60&&b.top<=120},{timeout:4000});await page.screenshot({path:`${out}/${n}.png`});record.scenes.push({name:n,text:await page.locator('body').innerText(),state:await saved()})}
async function load(g){await page.evaluate(s=>localStorage.setItem('ab-save',JSON.stringify(s)),g);await page.reload();await page.locator('#continue').click();await page.waitForTimeout(250)}
const previous=process.argv.includes('--guide-final')?JSON.parse(await readFile('workbench/howto-browser-results.json','utf8')):null;
async function check(name,fn){if(previous&&!name.startsWith('guide-')&&!name.startsWith('orange-')){record.checks.push(previous.checks.find(c=>c.name===name));record.scenes.push(...previous.scenes.filter(s=>!record.scenes.some(v=>v.name===s.name)));return}try{const detail=await fn();record.checks.push({name,passed:true,detail})}catch(e){record.checks.push({name,passed:false,error:e.stack});await shot('FAIL-'+name)}}
async function hover(g,x,y){const b=await page.locator('#board').boundingBox(),w=g.map.width,h=g.map.height,width=page.viewportSize().width,compact=width<=1100,z=compact?(w>=16?(width<=650?.72:.9):width<=650?1.05:1.25):w>=16?1.14:w<=9?1.6:1.35,cy=compact?-35:w>=16?20:5,s=Math.min(62,Math.max(39,b.width/(w*1.7)))*z,t=g.map.tiles[y*w+x];const px=b.x+b.width/2+(x-y-(w-h)/2)*s*.5,py=b.y+b.height*.48+cy+(x+y-(w+h)/2)*s*.24-t.h*s*.21;for(const [dx,dy] of [[0,-.5],[0,-.6],[0,0],[-.38,0],[.38,0],[0,-.18],[0,.18]]){const p={x:px+dx*s,y:py+dy*s};await page.mouse.move(p.x,p.y);if(await page.evaluate(()=>document.querySelector('#help strong')?.textContent)===`${x+1}:${y+1}`)return p}throw Error(`Cannot hover ${x}:${y}`)}
function stage(){const g=createGame({map:'tutorial',mode:'pvp',objective:'elimination'});g.map.tiles.forEach(t=>{t.h=0;t.terrain='grass';delete t.object;delete t.hp});g.units.forEach(u=>u.alive=false);const blue=g.units.find(u=>u.team==='blue'),red=g.units.find(u=>u.team==='red');for(const u of [blue,red])Object.assign(u,{alive:true,archetype:'sword',variant:'',modifier:undefined,artifact:undefined,hp:7,maxHp:7,guard:false,pinned:false,moved:false,acted:false,commander:false});Object.assign(blue,{x:3,y:3});Object.assign(red,{x:4,y:3});return{g,blue,red}}
async function select(id){await page.locator(`[data-unit="${id}"]`).click()}
try{
await page.goto('http://game.test/');await page.evaluate(g=>localStorage.setItem('ab-save',JSON.stringify(g)),stage().g);await page.reload();
for(const width of [1440,640])await check('guide-navigation-'+width,async()=>{await page.setViewportSize({width,height:width===640?800:900});await page.locator('#how-to').click();assert.equal(await page.locator('.guide-nav a').count(),8);const raw=await page.evaluate(()=>localStorage.getItem('ab-save'));const anchors=[];for(const link of await page.locator('.guide-nav a').all()){const href=await link.getAttribute('href');await link.click();await page.waitForTimeout(450);const bounds=await page.locator(href).evaluate(e=>{const b=e.getBoundingClientRect();return{top:b.top,left:b.left,right:b.right}});assert(bounds.top>=0&&bounds.top<page.viewportSize().height);anchors.push({href,bounds})}const layout=await page.evaluate(()=>({screenWidth:document.querySelector('.guide-screen').clientWidth,screenScrollWidth:document.querySelector('.guide-screen').scrollWidth,navScrollWidth:document.querySelector('.guide-nav').scrollWidth,navWidth:document.querySelector('.guide-nav').clientWidth}));assert.equal(layout.screenWidth,layout.screenScrollWidth);await shot(`01-guide-${width}-controls`);await page.locator('a[href="#guide-colors"]').click();await page.waitForTimeout(450);const colors=await page.locator('#guide-colors').innerText();assert.match(colors,/текущей позиции/);assert.match(colors,/Сам цвет не наносит урон/);assert.match(colors,/при остановке|прибыти|остановке/i);await shot(`02-guide-${width}-colors`);await page.keyboard.press('Escape');assert.equal(await page.locator('#how-to').count(),1);assert.equal(await page.evaluate(()=>localStorage.getItem('ab-save')),raw);await shot(`03-menu-${width}-return`);return{anchors,layout,colors}});
await page.setViewportSize({width:1440,height:900});
await check('guide-final-height-buttons-save',async()=>{await page.locator('#how-to').click();const before=await saved();await page.locator('a[href="#guide-height"]').click();await page.waitForTimeout(700);const text=await page.locator('#guide-height').innerText();assert.match(text,/при входе на клетку лестницы/);assert.doesNotMatch(text,/одна из двух клеток/);await shot('15-final-guide-height');await page.locator('#guide-back-bottom').click();assert.deepEqual(await saved(),before);assert.equal(await page.locator('#how-to').count(),1);await page.locator('#how-to').click();await page.locator('#guide-back').click();assert.deepEqual(await saved(),before);return{heightText:text}});
await check('sword-self-guard-adjacent-counter',async()=>{let {g,blue,red}=stage();await load(g);await select(blue.id);await page.keyboard.press('2');let p=await hover(g,blue.x,blue.y);assert.match(await page.locator('#preview-panel').innerText(),/Стража|стража/);await shot('04-sword-self-guard-preview');await page.mouse.click(p.x,p.y);g=await saved();assert.equal(g.units.find(u=>u.id===blue.id).guard,true);assert.equal(g.units.find(u=>u.id===blue.id).acted,true);assert.equal(g.units.find(u=>u.id===blue.id).moved,false);await page.keyboard.press('Enter');g=await saved();await select(red.id);p=await hover(g,blue.x,blue.y);assert.match(await page.locator('#preview-panel').innerText(),/Урон 2/);assert.match(await page.locator('#preview-panel').innerText(),/Ответ 1/);await shot('05-guard-counter-preview');await page.mouse.click(p.x,p.y);await page.waitForTimeout(200);g=await saved();assert.equal(g.units.find(u=>u.id===blue.id).hp,5);assert.equal(g.units.find(u=>u.id===red.id).hp,6);await shot('06-guard-counter-damage');await page.keyboard.press('Enter');assert.equal((await saved()).units.find(u=>u.id===blue.id).guard,false);return{history:g.history,blueHp:5,redHp:6}});
await check('distant-spear-does-not-counter',async()=>{let {g,blue,red}=stage();g.team='red';Object.assign(blue,{archetype:'spear',hp:6,maxHp:6,x:2,y:3});await load(g);await select(red.id);await page.keyboard.press('2');let p=await hover(g,red.x,red.y);await page.mouse.click(p.x,p.y);await page.keyboard.press('Enter');g=await saved();await select(blue.id);p=await hover(g,red.x,red.y);assert.doesNotMatch(await page.locator('#preview-panel').innerText(),/Ответ 1/);assert.match(await page.locator('#preview-panel').innerText(),/Урон 1/);await shot('07-distant-spear-preview');await page.mouse.click(p.x,p.y);g=await saved();assert.equal(g.units.find(u=>u.id===blue.id).hp,6);assert.equal(g.units.find(u=>u.id===red.id).hp,6);await shot('08-distant-spear-damage');return{history:g.history}});
await check('spear-thrust-pins-one-next-turn',async()=>{let {g,blue,red}=stage();Object.assign(blue,{archetype:'spear',hp:6,maxHp:6,x:3,y:3});Object.assign(red,{archetype:'scout',hp:4,maxHp:4,x:5,y:3});const ally=g.units.find(u=>u.id==='blue-2');Object.assign(ally,{alive:true,archetype:'sword',variant:'',hp:7,maxHp:7,x:6,y:4,commander:false});await load(g);await select(blue.id);await page.keyboard.press('2');let p=await hover(g,red.x,red.y);assert.match(await page.locator('#preview-panel').innerText(),/остановка движения до конца следующего хода цели/);await shot('09-thrust-preview');await page.mouse.click(p.x,p.y);g=await saved();assert.equal(g.units.find(u=>u.id===red.id).x,6);assert.equal(g.units.find(u=>u.id===red.id).pinned,true);await page.keyboard.press('Enter');g=await saved();await select(red.id);await hover(g,6,2);assert.match(await page.locator('#preview-panel').innerText(),/остановлен натиском/);await shot('10-pinned-next-turn-move');await page.keyboard.press('2');await hover(g,7,3);assert.match(await page.locator('#preview-panel').innerText(),/остановлен натиском.*рывок/i);await shot('11-pinned-next-turn-dash');await page.keyboard.press('1');p=await hover(g,ally.x,ally.y);assert.match(await page.locator('#preview-panel').innerText(),/Атака/);await page.mouse.click(p.x,p.y);assert.equal((await saved()).history.at(-1).type,'attack');await page.keyboard.press('Enter');assert.equal((await saved()).units.find(u=>u.id===red.id).pinned,false);await page.keyboard.press('Enter');g=await saved();await select(red.id);p=await hover(g,6,2);assert.match(await page.locator('#preview-panel').innerText(),/Маршрут/);await page.mouse.click(p.x,p.y);assert.equal((await saved()).units.find(u=>u.id===red.id).y,2);await shot('12-pinned-expired');return{history:(await saved()).history}});
await check('stairs-source-vs-destination-accuracy',async()=>{let {g,blue,red}=stage();red.x=7;red.y=7;g.map.tiles[3*8+3].terrain='stairs';g.map.tiles[3*8+4].h=2;await load(g);await select(blue.id);await hover(g,4,3);assert.match(await page.locator('#preview-panel').innerText(),/Приказ недоступен/);await shot('13-from-stairs-rise-two-blocked');let fixture=stage();g=fixture.g;blue=fixture.blue;fixture.red.x=7;fixture.red.y=7;Object.assign(g.map.tiles[3*8+4],{h:2,terrain:'stairs'});await load(g);await select(blue.id);await hover(g,4,3);assert.match(await page.locator('#preview-panel').innerText(),/Маршрут/);await shot('14-into-stairs-rise-two-allowed');return{fromStairs:'blocked',toStairs:'allowed'}});
await check('orange-threat-versus-hazard',async()=>{let {g,blue,red}=stage();Object.assign(red,{archetype:'archer',hp:4,maxHp:4,x:7,y:7});Object.assign(g.map.tiles[3*8+2],{object:'trap',trapDamage:2});await load(g);await select(blue.id);let p=await hover(g,4,4);const threat=await page.locator('#preview-panel').innerText();assert(legalMoves(g,blue.id).find(v=>v.x===4&&v.y===4)?.threatened);assert.match(threat,/Под ударом врага/);assert.doesNotMatch(threat,/Опасность/);await shot('16-orange-empty-threat');await page.mouse.click(p.x,p.y);assert.equal((await saved()).units.find(u=>u.id===blue.id).hp,7);await load(g);await select(blue.id);p=await hover(g,2,3);const hazard=await page.locator('#preview-panel').innerText();assert.match(hazard,/Опасность 2/);assert.doesNotMatch(hazard,/Под ударом врага/);await shot('17-orange-trap-hazard');await page.mouse.click(p.x,p.y);assert.equal((await saved()).units.find(u=>u.id===blue.id).hp,5);return{threatPreview:threat,hazardPreview:hazard}});
await check('final-guide-labels-and-alt',async()=>{await page.keyboard.press('Escape');await page.locator('[data-modal="menu"]').click();await page.locator('#how-to').click();const counter=await page.locator('#guide-counter').innerText(),classes=await page.locator('#guide-classes').innerText(),controls=await page.locator('#guide-goals').innerText();assert.match(counter,/Толчок \/ стража/);assert.match(classes,/базовые|Базовые/i);assert.match(controls,/Alt \+ ЛКМ/);await page.locator('a[href="#guide-counter"]').click();await page.waitForTimeout(900);await shot('18-final-counter-button-label');await page.keyboard.press('Escape');return{counter,classes,controls}});
await check('final-alt-gate-covered-ground',async()=>{const replay=JSON.parse(await readFile('workbench/current-campaign-replays/gate.json','utf8'));let g=createGame({map:'gate',mode:'ai',mission:'gate'});for(const c of replay.commands.slice(0,10))g=applyAction(g,c);assert.equal(g.team,'blue');assert.equal(g.history.length,10);const command={type:'move',unitId:'blue-4',x:7,y:3};assert.equal(previewAction(g,command).valid,true);await load(g);await select('blue-4');await page.keyboard.down('Alt');const p=await hover(g,7,3);assert.match(await page.locator('#preview-panel').innerText(),/Маршрут/);await shot('19-alt-gate-ground-preview');await page.mouse.click(p.x,p.y);await page.keyboard.up('Alt');await page.waitForTimeout(700);const after=await saved();assert.deepEqual(after.history.at(-1),command);const u=after.units.find(u=>u.id==='blue-4');assert.equal(u.x,7);assert.equal(u.y,3);await shot('20-alt-gate-ground-moved');return{command,preview:previewAction(g,command),history:after.history,unit:u}});
}finally{record.passed=record.checks.every(c=>c.passed)&&record.errors.length===0;await writeFile('workbench/howto-browser-results.json',JSON.stringify(record,null,2));await browser.close()}
console.log(JSON.stringify({passed:record.passed,errors:record.errors,checks:record.checks}));
