import {chromium} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {homedir} from 'node:os';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){if(s.startsWith('.')&&!/\.[cm]?[jt]s$/.test(s)){try{return next(s+'.ts',c)}catch{}try{return next(s+'/index.ts',c)}catch{}}return next(s,c)}});
const {createGame,applyAction}=await import('../src/engine/index.ts');
const out='workbench/story-shots';await mkdir(out,{recursive:true});
let browser;try{browser=await chromium.launch({headless:true})}catch{browser=await chromium.launch({headless:true,executablePath:join(homedir(),'AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe')})}
const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true}),page=await context.newPage();
const result={artifact:await readFile('dist/index.html','utf8'),checks:[],errors:[]};page.on('pageerror',e=>result.errors.push(e.message));
await page.route('**/*',async route=>{const path=new URL(route.request().url()).pathname.replace(/^\/medieval_tactics\//,'/'),name=path.slice(1)||'index.html';try{await route.fulfill({body:await readFile(resolve('dist',name)),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.svg')?'image/svg+xml':'text/html'})}catch{result.errors.push('missing '+name);await route.fulfill({status:404,body:'missing'})}});
await page.addInitScript(()=>{window.audioAudit={contexts:0,resumes:0,outputs:[]};const Real=window.AudioContext;window.AudioContext=class extends Real{constructor(...args){super(...args);window.audioAudit.contexts++}resume(){window.audioAudit.resumes++;return super.resume()}createGain(){const gain=super.createGain(),connect=gain.connect.bind(gain),ctx=this;gain.connect=(destination,...args)=>{if(destination===ctx.destination){const analyser=ctx.createAnalyser();connect(analyser);analyser.connect(destination);window.audioAudit.outputs.push(analyser);return destination}return connect(destination,...args)};return gain}}});
const tap=selector=>page.locator(selector).tap();
const story=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ab-story')));
async function shot(name){await page.screenshot({path:`${out}/${name}.png`})}
async function check(name,fn){try{result.checks.push({name,passed:true,detail:await fn()})}catch(e){result.checks.push({name,passed:false,error:e.stack});await shot('FAIL-'+name)}}
async function finishScene(){for(let i=0;i<30&&await page.locator('.novel').count();i++){if(await page.locator('[data-story-choice]:enabled').count())await tap('[data-story-choice="people"]');await tap('#story-next')}assert.equal(await page.locator('.novel').count(),0)}
try{
await page.goto('http://game.test/');
await check('intro-resume-log-keyboard-and-battle',async()=>{await tap('#campaign');await tap('[data-campaign-id="embers"]');await tap('#campaign-start');assert.equal(await page.locator('.novel').count(),1);assert.equal(await page.locator('#board').count(),0);await shot('01-river-prologue');await tap('#story-next');assert.equal((await story()).cursor.index,1);await tap('#story-log');assert.match(await page.locator('.novel-log').innerText(),/Верен/);await tap('#story-log-close');await tap('#story-menu');await page.reload();await tap('#continue-story');assert.equal((await story()).cursor.index,1);await page.keyboard.press('ArrowLeft');assert.equal((await story()).cursor.index,0);await page.locator('.novel-line').click();await page.keyboard.press('Space');assert.equal((await story()).cursor.index,1);await finishScene();const save=await page.evaluate(()=>JSON.parse(localStorage.getItem('ab-save')));assert.equal(save.campaignMission,'ford');assert.equal(save.history.length,0);assert.equal((await story()).cursor,null);await tap('#pause');await tap('[data-modal="menu"]');return{mission:save.campaignMission}});
const ids=['ford','watch','steps','gate','marsh','kiln'];
await page.evaluate(ids=>localStorage.setItem('ab-campaign',JSON.stringify({version:1,completed:ids})),ids);await tap('#campaign');await tap('[data-campaign-id="embers"]');
await check('all-intro-outro-scenes-and-ambient-changes',async()=>{const profiles=[],rms=[];for(const [i,id]of ids.entries()){await tap(`[data-mission="${i}"]`);await tap('#read-intro');profiles.push(await page.locator('.novel').getAttribute('data-ambience'));await page.waitForTimeout(300);const level=await page.evaluate(()=>window.audioAudit.outputs.reduce((sum,a)=>{const data=new Float32Array(a.fftSize);a.getFloatTimeDomainData(data);return sum+Math.sqrt(data.reduce((s,v)=>s+v*v,0)/data.length)},0));assert(level>1e-7,id);rms.push(level);if(id==='gate'){assert.equal(await page.locator('#story-skip').isDisabled(),true);while(!await page.locator('[data-story-choice]').count())await tap('#story-next');assert.equal(await page.locator('#story-next').isDisabled(),true);await tap('[data-story-choice="people"]');assert.equal((await story()).choices.signal,'people');await shot('02-signal-choice')}await finishScene();await tap('#read-outro');if(id==='kiln')await shot('03-kiln-epilogue');await finishScene()}assert.equal(new Set(profiles).size,4);const p=await story();assert.equal(p.seen.filter(id=>!id.endsWith(':defeat')).length,12);const audit=await page.evaluate(()=>({contexts:window.audioAudit.contexts,resumes:window.audioAudit.resumes}));assert.equal(audit.contexts,1);assert(audit.resumes>=4);return{profiles,rms,seen:p.seen,audio:audit}});
await check('tablet-dialogue-layout-and-live-images',async()=>{for(const viewport of [{width:768,height:1024},{width:1024,height:768},{width:390,height:844}]){await page.setViewportSize(viewport);await tap('[data-mission="5"]');await tap('#read-intro');for(const id of ['story-next','story-back','story-skip','story-menu','story-log']){const b=await page.locator('#'+id).boundingBox();assert(b&&b.x>=0&&b.y>=0&&b.x+b.width<=viewport.width+1&&b.y+b.height<=viewport.height+1,id);const hit=await page.evaluate(({id,b})=>{const e=document.getElementById(id),top=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return top===e||e.contains(top)},{id,b});assert(hit,id)}const loaded=await page.locator('.novel-art').evaluate(async e=>{const url=getComputedStyle(e).backgroundImage.match(/url\("?([^"\)]+)/)[1];const img=new Image();img.src=url;await img.decode();return img.naturalWidth});assert(loaded>1000);await shot('04-dialogue-'+viewport.width);await tap('#story-skip')}return{sizes:[768,1024,390]}});
await check('choice-alternative-reply-and-reduced-motion',async()=>{await page.evaluate(()=>{localStorage.setItem('ab-story',JSON.stringify({version:1,seen:[],choices:{signal:'orders'},cursor:{mission:'kiln',phase:'outro',index:6,destination:'campaign'}}));localStorage.setItem('ab-reduce-motion','1')});await page.reload();await tap('#continue-story');assert.match(await page.locator('.novel-line').innerText(),/ложный сигнал тоже попадёт в отчёт/);assert.equal(await page.locator('.novel').evaluate(e=>e.classList.contains('still')),true);await shot('05-alternative-epilogue');await tap('#story-menu');return{choice:(await story()).choices.signal}});
await check('defeat-restoration-retreat-and-restart',async()=>{let loss=createGame({map:'ford',mode:'ai',mission:'ford'});for(let i=0;i<24;i++)loss=applyAction(loss,{type:'endTurn'});assert.equal(loss.winner,'red');await page.evaluate(s=>{localStorage.setItem('ab-save',JSON.stringify(s));localStorage.setItem('ab-campaign',JSON.stringify({version:1,completed:[]}))},loss);await page.reload();await tap('#continue');await page.locator('[data-modal="campaign-story"]').waitFor();await tap('[data-modal="campaign-story"]');assert.equal((await story()).cursor.phase,'defeat');await shot('06-retreat');await finishScene();assert.equal(await page.locator('.campaign-screen').count(),1);await tap('#campaign-start');await tap('#story-skip');const fresh=await page.evaluate(()=>JSON.parse(localStorage.getItem('ab-save')));assert.equal(fresh.history.length,0);assert.equal(fresh.winner,undefined);return{winner:loss.winner,newMission:fresh.campaignMission}});
await check('audio-fades-in-pause-and-menu',async()=>{const measure=()=>page.evaluate(()=>window.audioAudit.outputs.reduce((sum,a)=>{const data=new Float32Array(a.fftSize);a.getFloatTimeDomainData(data);return sum+Math.sqrt(data.reduce((s,v)=>s+v*v,0)/data.length)},0));await page.waitForTimeout(400);const active=await measure();assert(active>1e-7);await tap('#pause');await page.waitForTimeout(1100);const paused=await measure();assert(paused<active*.05);await tap('[data-modal="resume"]');await page.waitForTimeout(400);assert(await measure()>1e-7);await tap('#pause');await tap('[data-modal="menu"]');await page.waitForTimeout(1100);const menu=await measure();assert(menu<active*.05);return{active,paused,menu}});
}finally{result.passed=result.checks.every(c=>c.passed)&&result.errors.length===0;await writeFile(`${out}/results.json`,JSON.stringify(result,null,2));await browser.close()}
console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1;
