import {chromium} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {homedir} from 'node:os';
import {registerHooks} from 'node:module';
import assert from 'node:assert/strict';
registerHooks({resolve(s,c,next){if(s.startsWith('.')&&!/\.[cm]?[jt]s$/.test(s)){try{return next(s+'.ts',c)}catch{}try{return next(s+'/index.ts',c)}catch{}}return next(s,c)}});
const {createGame,legalMoves,applyAction}=await import('../src/engine/index.ts');
let browser;try{browser=await chromium.launch({headless:true})}catch{browser=await chromium.launch({headless:true,executablePath:join(homedir(),'AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe')})}
const out='workbench/tablet-shots';await mkdir(out,{recursive:true});
const record={artifact:await readFile('dist/index.html','utf8'),checks:[],scenes:[],errors:[]};
async function configure(page){page.on('pageerror',e=>record.errors.push(e.message));await page.route('**/*',async r=>{const name=new URL(r.request().url()).pathname.replace(/^\/medieval_tactics\//,'/').slice(1)||'index.html';try{await r.fulfill({body:await readFile(resolve('dist',name)),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.svg')?'image/svg+xml':'text/html'})}catch{record.errors.push('missing '+name);await r.fulfill({status:404,body:'missing'})}});await page.addInitScript(()=>{localStorage.setItem('ab-volume','0');localStorage.setItem('ab-reduce-motion','1')});}
const context=await browser.newContext({hasTouch:true,isMobile:true,viewport:{width:768,height:1024},deviceScaleFactor:1}),page=await context.newPage();await configure(page);const cdp=await context.newCDPSession(page);
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ab-save')));
async function shot(name){await page.screenshot({path:`${out}/${name}.png`});record.scenes.push({name,text:await page.locator('body').innerText(),state:await saved(),layout:await page.evaluate(()=>Object.fromEntries(['touch-confirm','touch-clear','touch-ground','touch-bridge','touch-heights','inspect-toggle','end-turn','objective-panel','preview-panel'].map(id=>{const e=document.getElementById(id),b=e?.getBoundingClientRect();return[id,e?{x:b.x,y:b.y,width:b.width,height:b.height,display:getComputedStyle(e).display,disabled:e.disabled}:null]})))})}
async function check(name,fn){try{const detail=await fn();record.checks.push({name,passed:true,detail})}catch(e){record.checks.push({name,passed:false,error:e.stack});await shot('FAIL-'+name)}}
async function tap(selector){const loc=page.locator(selector);try{await loc.scrollIntoViewIfNeeded()}catch(e){if(!/not attached/.test(e.message))throw e;await loc.scrollIntoViewIfNeeded()}const b=await loc.boundingBox();assert(b);await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2)}
async function load(g){if(await page.locator('#board').count()){if(!await page.locator('[data-modal="menu"]').count())await tap('#pause');await tap('[data-modal="menu"]')}await page.evaluate(s=>localStorage.setItem('ab-save',JSON.stringify(s)),g);await page.reload();await tap('#continue');await page.waitForTimeout(150)}
function projected(g,x,y,desktop=false){const w=g.map.width,h=g.map.height,width=page.viewportSize().width,z=desktop?(w>=16?1.14:w<=9?1.6:1.35):(w>=16?(width<=650?.72:width>1100?1.1:.9):width<=650?1.05:1.25);return page.locator('#board').boundingBox().then(b=>{const s=Math.min(62,Math.max(39,b.width/(w*1.7)))*z,t=g.map.tiles[y*w+x],cy=desktop?(w>=16?20:5):(b.height-(width<=700?380:355))*.55-b.height*.48;return{x:b.x+b.width/2+(x-y-(w-h)/2)*s*.5,y:b.y+b.height*.48+cy+(x+y-(w+h)/2)*s*.24-t.h*s*.21,s}})}
async function tapCell(g,x,y){const p=await projected(g,x,y);for(const [dx,dy]of [[0,-.5],[0,-.6],[0,0],[-.38,0],[.38,0],[0,-.18],[0,.18]]){await page.touchscreen.tap(p.x+dx*p.s,p.y+dy*p.s);if(await page.evaluate(()=>document.querySelector('#help strong')?.textContent)===`${x+1}:${y+1}`)return}throw Error(`Cannot tap ${x}:${y}`)}
async function inspector(open){if((await page.locator('#inspect-toggle').getAttribute('aria-expanded')==='true')!==open)await tap('#inspect-toggle')}
async function mode(name){await inspector(true);await tap(`[data-action="${name}"]`);await inspector(false)}
function stage(){const g=createGame({map:'tutorial',mode:'pvp',objective:'elimination'});g.map.tiles.forEach(t=>{t.h=0;t.terrain='grass';delete t.object;delete t.hp});g.units.forEach(u=>u.alive=false);const blue=g.units.find(u=>u.team==='blue'),red=g.units.find(u=>u.team==='red');for(const u of [blue,red])Object.assign(u,{alive:true,archetype:'sword',variant:'',modifier:undefined,artifact:undefined,hp:7,maxHp:7,guard:false,pinned:false,moved:false,acted:false,commander:false});Object.assign(blue,{x:3,y:3});Object.assign(red,{x:4,y:3});return{g,blue,red}}
async function gesture(points,kind='touchEnd'){const first=points[0];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:first.map((p,i)=>({...p,id:i+1}))});for(const frame of points.slice(1)){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:frame.map((p,i)=>({...p,id:i+1}))});await page.waitForTimeout(30)}await cdp.send('Input.dispatchTouchEvent',{type:kind,touchPoints:[]});await page.waitForTimeout(80)}
try{
await page.goto('http://game.test/');
for(const viewport of [{width:768,height:1024},{width:1024,height:768}])await check('layout-menu-guide-'+viewport.width,async()=>{await page.setViewportSize(viewport);await page.reload();await shot(`01-menu-${viewport.width}`);await tap('#how-to');const before=await page.locator('.guide-screen').evaluate(e=>e.scrollTop);await gesture([[{x:viewport.width*.7,y:viewport.height*.75}],[{x:viewport.width*.7,y:viewport.height*.5}],[{x:viewport.width*.7,y:viewport.height*.25}]]);const after=await page.locator('.guide-screen').evaluate(e=>e.scrollTop);assert(after>before);await shot(`02-guide-native-scroll-${viewport.width}`);await tap('#guide-back');await load(createGame({map:'highland',mode:'pvp',objective:'control'}));const controls=await page.evaluate(()=>Object.fromEntries(['touch-attack','touch-ability','touch-confirm','touch-clear','touch-ground','touch-bridge','touch-heights','inspect-toggle','end-turn'].map(id=>{const e=document.getElementById(id),b=e.getBoundingClientRect(),top=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return[id,{x:b.x,y:b.y,right:b.right,bottom:b.bottom,height:b.height,reachable:top===e||e.contains(top)}]})));for(const [id,b]of Object.entries(controls)){assert(b.x>=0&&b.right<=viewport.width&&b.y>=0&&b.bottom<=viewport.height,id);assert(b.reachable,id)}await tap('#touch-heights');assert.equal(await page.locator('#touch-heights').getAttribute('aria-pressed'),'true');await tap('#touch-heights');await shot(`03-battle-hud-${viewport.width}`);return{before,after,controls}});
await page.setViewportSize({width:768,height:1024});
await check('all-six-abilities-from-persistent-toolbar',async()=>{const results=[];for(const archetype of ['sword','archer','spear','shield','scout','engineer']){const {g,blue,red}=stage();blue.archetype=archetype;red.x=7;red.y=7;let target={x:blue.x,y:blue.y};if(archetype==='archer'||archetype==='spear'){red.x=5;red.y=3;target={x:red.x,y:red.y}}if(archetype==='scout')target={x:5,y:3};if(archetype==='engineer')target={x:4,y:3};await load(g);await tapCell(g,blue.x,blue.y);assert.equal(await page.locator('#selection-panel').isVisible(),false);await tap('#touch-ability');assert.equal(await page.locator('#touch-ability').getAttribute('aria-pressed'),'true');await tapCell(g,target.x,target.y);assert.equal(await page.locator('#touch-confirm').isEnabled(),true,archetype);assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));const cmd={type:'ability',unitId:blue.id,...target};const expected=applyAction(g,cmd);await shot('ability-'+archetype+'-preview');await tap('#touch-confirm');assert.deepEqual(await saved(),JSON.parse(JSON.stringify(expected)),archetype);assert.equal(await page.locator('#touch-ability').isDisabled(),true);results.push({archetype,command:cmd})}return{results}});
await check('menu-long-press-no-selection-and-favicon',async()=>{await load(createGame({map:'tutorial',mode:'pvp'}));await tap('#pause');await tap('[data-modal="menu"]');const box=await page.locator('.menu h1').boundingBox();assert(box);const point={x:box.x+box.width/2,y:box.y+box.height/2,id:1};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point]});await page.waitForTimeout(950);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>window.getSelection()?.toString()),'');assert.equal(await page.locator('#app').evaluate(e=>getComputedStyle(e).userSelect),'none');const icon=await page.locator('link[rel="icon"]').getAttribute('href');assert.match(icon,/\/medieval_tactics\/favicon\.svg$/);const response=await page.evaluate(async()=>{const url=document.querySelector('link[rel="icon"]').href;const r=await fetch(url);return{status:r.status,text:await r.text()}});assert.equal(response.status,200);assert.match(response.text,/<svg/);await shot('21-menu-long-press-favicon');return{icon,selection:''}});
await check('move-preview-confirm-undo-clear',async()=>{const {g,blue,red}=stage();red.x=7;red.y=7;await load(g);await tapCell(g,blue.x,blue.y);assert.match(await page.locator('#selection-panel').innerText(),/BLUE-1/i);await tapCell(g,3,2);assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));assert.equal(await page.locator('#touch-confirm').isEnabled(),true);assert.match(await page.locator('#preview-panel').innerText(),/Маршрут/);await shot('04-touch-move-preview');await tap('#touch-confirm');let after=await saved();assert.equal(after.history.length,1);assert.deepEqual(after.history[0],{type:'move',unitId:blue.id,x:3,y:2});await shot('05-touch-move-committed');await tap('#undo');after=await saved();assert.equal(after.units.find(u=>u.id===blue.id).y,3);await tapCell(after,3,2);assert.equal(await page.locator('#touch-confirm').isEnabled(),true);await tap('#touch-clear');assert.equal(await page.locator('#touch-confirm').isDisabled(),true);assert.match(await page.locator('#selection-panel').innerText(),/Выберите бойца/);await shot('06-touch-undo-cleared');return{history:after.history}});
await check('sword-guard-and-pvp-red-attack',async()=>{const {g,blue,red}=stage();await load(g);await tapCell(g,blue.x,blue.y);assert.equal(await page.locator('#selection-panel').isVisible(),false);await tap('#touch-ability');assert.match(await page.locator('#touch-ability').innerText(),/Толчок/);await tapCell(g,blue.x,blue.y);assert.equal((await saved()).history.length,0);assert.match(await page.locator('#preview-panel').innerText(),/Стража/);assert.equal(await page.locator('#touch-confirm').isEnabled(),true);await shot('07-touch-guard-preview');await tap('#touch-confirm');assert.equal((await saved()).units.find(u=>u.id===blue.id).guard,true);await tap('#end-turn');let after=await saved();assert.equal(after.team,'red');assert.equal(await page.locator('#end-turn').isEnabled(),true);await tapCell(after,red.x,red.y);await tapCell(after,blue.x,blue.y);assert.equal((await saved()).history.length,2);assert.match(await page.locator('#preview-panel').innerText(),/Ответ 1/);await shot('08-touch-red-attack-preview');await tap('#touch-confirm');after=await saved();assert.equal(after.units.find(u=>u.id===blue.id).hp,5);assert.equal(after.units.find(u=>u.id===red.id).hp,6);await tap('#end-turn');assert.equal((await saved()).team,'blue');await shot('09-touch-red-attack-committed');return{history:after.history}});
await check('touch-ai-orders-blocked',async()=>{await load(createGame({map:'highland',mode:'ai',objective:'control'}));await tap('#end-turn');assert.equal((await saved()).team,'red');assert.equal(await page.locator('#touch-confirm').isDisabled(),true);assert.equal(await page.locator('#end-turn').isDisabled(),true);const g=await saved(),red=g.units.find(u=>u.team==='red');await tapCell(g,red.x,red.y);assert.equal(await page.locator('#touch-confirm').isDisabled(),true);await shot('10-touch-ai-blocked');return{history:(await saved()).history}});
await check('native-pan-pinch-cancel-no-command',async()=>{const {g,blue,red}=stage();red.x=7;red.y=7;await load(g);await tapCell(g,blue.x,blue.y);await tapCell(g,3,2);assert.equal(await page.locator('#touch-confirm').isEnabled(),true);const p=await projected(g,3,2);await gesture([[{x:p.x,y:p.y}],[{x:p.x+35,y:p.y+10}],[{x:p.x+70,y:p.y+20}]]);assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));assert.equal(await page.locator('#touch-confirm').isDisabled(),true);const anchor=await projected(g,blue.x,blue.y);await page.touchscreen.tap(anchor.x+70,anchor.y+20-anchor.s*.5);assert.match(await page.locator('#selection-panel').innerText(),/BLUE-1/i);await shot('11-touch-pan');await gesture([[{x:330,y:330},{x:430,y:330}],[{x:310,y:330},{x:450,y:330}],[{x:280,y:330},{x:480,y:330}]]);assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));assert.equal(await page.locator('#touch-confirm').isDisabled(),true);await shot('12-touch-pinch');await gesture([[{x:430,y:330}]],'touchCancel');assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));assert.equal(await page.locator('#touch-confirm').isDisabled(),true);await shot('13-touch-cancel');return{history:(await saved()).history}});
await check('ground-toggle-gate-covered-cell',async()=>{const replay=JSON.parse(await readFile('workbench/current-campaign-replays/gate.json','utf8'));let g=createGame({map:'gate',mode:'ai',mission:'gate'});for(const c of replay.commands.slice(0,10))g=applyAction(g,c);await load(g);await inspector(true);await tap('[data-unit="blue-4"]');await inspector(false);await tap('#touch-ground');assert.equal(await page.locator('#touch-ground').getAttribute('aria-pressed'),'true');await tapCell(g,7,3);assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));assert.match(await page.locator('#preview-panel').innerText(),/Маршрут/);await shot('14-touch-ground-preview');await tap('#touch-confirm');const after=await saved();assert.deepEqual(after.history.at(-1),{type:'move',unitId:'blue-4',x:7,y:3});await shot('15-touch-ground-moved');return{history:after.history}});
await check('bridge-attack-toggle',async()=>{const {g,blue,red}=stage();red.x=7;red.y=7;Object.assign(g.map.tiles[3*8+4],{terrain:'bridge',object:'fragile',hp:2});await load(g);await tapCell(g,blue.x,blue.y);await tapCell(g,4,3);assert.match(await page.locator('#touch-confirm').innerText(),/шаг/);assert.equal((await saved()).history.length,0);await tap('#touch-bridge');assert.equal(await page.locator('#touch-confirm').isDisabled(),true);await tapCell(g,4,3);assert.match(await page.locator('#preview-panel').innerText(),/Атака/);assert.match(await page.locator('#touch-confirm').innerText(),/атаку/);await shot('16-touch-bridge-attack-preview');await tap('#touch-confirm');const after=await saved();assert.equal(after.map.tiles[3*8+4].terrain,'water');assert.equal(after.history.at(-1).type,'attack');await shot('17-touch-bridge-collapsed');return{history:after.history}});
await check('rotate-clears-pending-and-pause-menu',async()=>{const {g,blue,red}=stage();red.x=7;red.y=7;await load(g);await tapCell(g,blue.x,blue.y);await tapCell(g,3,2);assert.equal(await page.locator('#touch-confirm').isEnabled(),true);await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(120);assert.equal(await page.locator('#touch-confirm').isDisabled(),true);assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));await shot('19-rotated-preview-cleared');await tap('#pause');const controls=await page.locator('[data-modal]').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect(),top=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return{action:e.dataset.modal,x:b.x,y:b.y,right:b.right,bottom:b.bottom,reachable:top===e||e.contains(top)}}));for(const b of controls){assert(b.reachable&&b.x>=0&&b.right<=1024&&b.y>=0&&b.bottom<=768)}await shot('20-native-touch-pause');await tap('[data-modal="resume"]');assert.deepEqual(await saved(),JSON.parse(JSON.stringify(g)));await page.setViewportSize({width:768,height:1024});return{controls}});
await check('native-rule-tag-descriptions',async()=>{const {g,blue,red}=stage();red.x=7;red.y=7;Object.assign(blue,{variant:'warden',modifier:'heavy',artifact:'boots',hp:8,maxHp:8});await load(g);await tapCell(g,blue.x,blue.y);await inspector(true);const descriptions=[];for(let i=0;i<3;i++){const tags=page.locator('.rule-tag'),expected=await tags.nth(i).getAttribute('title');const b=await tags.nth(i).boundingBox();await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);assert.equal(await page.locator('.rule-detail').innerText(),expected);descriptions.push(expected)}await shot('21-native-rule-tag-detail');await inspector(false);return{descriptions}});
await check('desktop-mouse-one-click-unchanged',async()=>{const desktop=await browser.newContext({viewport:{width:1440,height:900}}),mousePage=await desktop.newPage();await configure(mousePage);await mousePage.goto('http://game.test/');const {g,blue,red}=stage();red.x=7;red.y=7;await mousePage.evaluate(s=>localStorage.setItem('ab-save',JSON.stringify(s)),g);await mousePage.reload();await mousePage.locator('#continue').click();await mousePage.locator('[data-unit="blue-1"]').click();const b=await mousePage.locator('#board').boundingBox(),s=Math.min(62,Math.max(39,b.width/(g.map.width*1.7)))*1.6,x=b.x+b.width/2+(3-2)*s*.5,y=b.y+b.height*.48+5+(3+2-8)*s*.24;await mousePage.mouse.move(x,y);await mousePage.mouse.click(x,y);const after=await mousePage.evaluate(()=>JSON.parse(localStorage.getItem('ab-save')));assert.deepEqual(after.history.at(-1),{type:'move',unitId:blue.id,x:3,y:2});assert.equal(await mousePage.locator('#touch-confirm').isVisible(),false);await mousePage.screenshot({path:`${out}/18-desktop-mouse-committed.png`});await desktop.close();return{history:after.history}});
}finally{record.passed=record.checks.every(c=>c.passed)&&record.errors.length===0;await writeFile(`${out}/results.json`,JSON.stringify(record,null,2));await browser.close()}
console.log(JSON.stringify({passed:record.passed,errors:record.errors,checks:record.checks}));
