import './style.css';
import './story.css';
import { getLanguage, setLanguage, translate, installLocalization, type Language } from './i18n';
import { storyScene, ambienceForMission, type StoryPhase } from './story-data';
import { beginStory, chooseStory, stepStory, endStory, restoreStoryProgress, unansweredChoice, type StoryProgress } from './story-progress';
import { storyHTML } from './story-ui';
import { AmbientPlayer } from './ambience';
import { scenarioObjectiveHTML } from './campaign-objective-ui';
import { campaignUnitName } from './unit-label';
import { createGame, legalMoves, previewAction, applyAction, undoMove, replayGame, getUnitRules, tileHazardDamage, choiceCost, ARCHETYPES, VARIANTS, MODIFIERS, ARTIFACTS, PRESETS, BUDGET, rosterCost, validateBlueprint, CAMPAIGN_MISSIONS, getCampaignMission, damageEvents } from './engine';
import type { Archetype, Blueprint, Command, GameState, MapId, Tile, Unit, UnitChoice, Preview } from './engine';
import { restoreCampaignProgress, missionUnlocked, recordCampaignVictory, nextCampaignMissionId, resetCampaignProgress, selectCampaignRoute, type CampaignRoute } from './campaign-progress';
import { campaignScreenHTML, campaignLessonHTML, campaignResultHTML, renderNewCampaignConfirmation } from './campaign-ui';
import { chooseAiCommand } from './ai';
import { drawFighterSprite, spriteAssetsReady, recordSpriteCommand, resetSpriteAnimations, spriteDeathVisible } from './fighter-sprites';
import { drawPropSprite, terrainSprite } from './environment-sprites';
import { howToHTML } from './how-to';
import { bindTouchControls } from './touch-controls';
import type { Difficulty } from './ai';

const app = document.querySelector<HTMLDivElement>('#app')!;
installLocalization(app);
document.documentElement.lang=getLanguage();
document.title=translate('Пепел и знамя');
const NAMES: Record<Archetype,string> = {archer:'Лучник',sword:'Мечник',spear:'Копейщик',shield:'Щитоносец',scout:'Разведчик',engineer:'Инженер'};
const GLYPHS: Record<Archetype,string> = {archer:'⌁',sword:'⚔',spear:'♜',shield:'⬡',scout:'➶',engineer:'⚒'};
const TERRAIN: Record<string,string> = {grass:'трава',stone:'камень',water:'вода',bridge:'мост',stairs:'лестница',rubble:'обломки'};
type Screen = 'menu'|'roster'|'battle'|'campaign'|'howto'|'story';
let screen: Screen = 'menu', state: GameState | null = null, selected: string | null = null, hovered: {x:number;y:number}|null = null;
let mode: 'ai'|'pvp' = 'ai', mapId: MapId = 'highland', rosterTeam: 'blue'|'red' = 'blue';
let campaignFocus=0;
let storyLog=false;
const storyProgress=()=>{const p=restoreStoryProgress(localStorage.getItem('ab-story')),route=campaignProgress().route;return route?{...p,choices:{...p.choices,route}}:p;};
const saveStory=(progress:StoryProgress)=>localStorage.setItem('ab-story',JSON.stringify(progress));
let battleEpoch=0, runningAiEpoch:number|null=null;
const playerCanAct=()=>screen==='battle'&&!!state&&!state.winner&&!modal&&!replayMode&&!(state.mode==='ai'&&state.team==='red');
const campaignProgress=()=>restoreCampaignProgress(localStorage.getItem('ab-campaign'));
let resultTimer:ReturnType<typeof setTimeout>|undefined;
let matchObjective: GameState['objective']['kind'] = (['control','commander','elimination'].includes(localStorage.getItem('ab-objective')??'') ? localStorage.getItem('ab-objective') : 'control') as GameState['objective']['kind'];
let aiDifficulty: Difficulty = (localStorage.getItem('ab-difficulty') as Difficulty)||'normal';
let blueRoster: Blueprint = structuredClone(PRESETS[0]), redRoster: Blueprint = structuredClone(PRESETS[1]);
let roster: Blueprint = blueRoster, draft: UnitChoice = {archetype:'archer',variant:'hunter'};
let actionMode: 'attack'|'ability' = 'attack', preview: Preview|null = null, modal: 'pause'|'result'|'settings'|null = null;
let shiftHeld=false;
let touchMode=navigator.maxTouchPoints>0||window.matchMedia('(pointer: coarse)').matches;
let touchGround=false,touchBridge=false,touchHeights=false;
let touchOrder:{command:Command;state:GameState;mode:'attack'|'ability'}|null=null;
document.documentElement.classList.toggle('touch-input',touchMode);
let showAllHeights=false, inspectorOpen=false;
let replayMode=false,replayCommands:Command[]=[],replayIndex=0,replayInitial:NonNullable<GameState['initial']>|null=null;
let camera = {x:0,y:10,zoom:1}, drag: {x:number;y:number;ox:number;oy:number;down:boolean}|null = null;
let canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D, raf=0, mouse={x:0,y:0}, moveCells: ReturnType<typeof legalMoves>=[];
let audioContext: AudioContext|null=null, soundVolume=Number(localStorage.getItem('ab-volume')??'0.35'), animationSpeed=Number(localStorage.getItem('ab-speed')??'1');
let musicVolume=Number(localStorage.getItem('ab-music-volume')??localStorage.getItem('ab-volume')??'0.35');
let highContrast=localStorage.getItem('ab-contrast')==='1',reduceMotion=localStorage.getItem('ab-reduce-motion')==='1';
document.documentElement.classList.toggle('high-contrast',highContrast);
let activePulse: {x:number;y:number;kind:string;at:number}|null=null;
type DamageNumber={x:number;y:number;h:number;amount:number;source:string;at:number;team:'blue'|'red';fatal:boolean};
const damageNumbers:DamageNumber[]=[];
function noteDamage(before:GameState,after:GameState){
  const command=after.history.at(-1);if(!command)return;
  const grouped=new Map<string,ReturnType<typeof damageEvents>>();
  for(const event of damageEvents(before,after,command))grouped.set(event.unitId,[...(grouped.get(event.unitId)??[]),event]);
  for(const [id,events]of grouped){const unit=after.units.find(u=>u.id===id)!;const last=events.at(-1)!;
    const motion=motions.get(id),delay=!replayMode&&motion?Math.max(0,motion.at+motion.duration-performance.now()):0;
    damageNumbers.push({x:last.x,y:last.y,h:last.h,amount:events.reduce((sum,e)=>sum+e.amount,0),source:[...new Set(events.map(e=>e.source))].join(' + '),at:performance.now()+delay,team:unit.team,fatal:!unit.alive});
  }
}
type MotionPoint={x:number;y:number;h:number};
type Motion={points:MotionPoint[];at:number;duration:number};
const motions=new Map<string,Motion>();
const clone = <T>(x:T):T => JSON.parse(JSON.stringify(x));
const unitAt=(x:number,y:number)=>state?.units.find(u=>u.alive&&u.x===x&&u.y===y);
const tileAt=(x:number,y:number)=>state?.map.tiles.find(t=>t.x===x&&t.y===y);
const chosen=()=>state?.units.find(u=>u.id===selected);
const isMine=(u:Unit)=>u.team===state?.team;
const reinforcing=(u:Unit|undefined,t:Tile|undefined)=>actionMode==='ability'&&u?.archetype==='engineer'&&u.variant==='mason'&&(t?.object==='cover'||t?.object==='fragile');
const save=()=>{if(state)localStorage.setItem('ab-save',JSON.stringify(state));};
function tone(freq=360,duration=.09,wave:OscillatorType='sine',volume=.17){if(!soundVolume)return;try{audioContext??=new AudioContext();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=wave;o.frequency.setValueAtTime(freq,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(80,freq*.6),audioContext.currentTime+duration);g.gain.setValueAtTime(volume*soundVolume,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration)}catch{}}
const ambientPlayer=new AmbientPlayer(()=>audioContext??=new AudioContext(),()=>musicVolume);
function stopMusic(){ambientPlayer.stop()}
function startMusic(){const progress=storyProgress(),cursor=progress.cursor;const id=screen==='story'?cursor?.mission:state?.campaignMission??state?.map.id;const speaker=screen==='story'&&cursor?storyScene(cursor.mission,cursor.phase,progress.choices)?.lines[cursor.index].speaker:undefined;const route=campaignProgress().route;const motif=id==='summit'&&screen==='story'&&cursor?.phase==='outro'?'ending':speaker??(id==='caravan'||id==='granary'?id:id==='evacuation'?route??undefined:undefined);ambientPlayer.start(ambienceForMission(id),motif)}
function setScreen(next:Screen){screen=next;if(next!=='battle'){battleEpoch++;stopMusic()}cancelAnimationFrame(raf);render();}
function battleCamera(){const size=state?.map.width??18,compact=touchMode||window.innerWidth<=1100;const canvasHeight=window.innerHeight-(window.innerWidth<=650?60:76),reserved=window.innerWidth<=700?380:355;return{x:0,y:touchMode?(canvasHeight-reserved)*.55-canvasHeight*.48:compact?-35:size>=16?20:5,zoom:compact?(size>=16?(window.innerWidth<=650?.72:window.innerWidth>1100?1.1:.9):window.innerWidth<=650?1.05:1.25):size>=16?1.14:size<=9?1.6:1.35}}
function prepareBattle(){battleEpoch++;touchOrder=null;touchGround=false;touchBridge=false;inspectorOpen=false;clearTimeout(resultTimer);replayMode=false;resetSpriteAnimations();motions.clear();damageNumbers.length=0;selected=null;hovered=null;preview=null;moveCells=[];modal=null;camera=battleCamera()}
function begin(kind:MapId,gameMode:'ai'|'pvp'){mapId=kind;mode=gameMode;state=createGame({map:kind,mode:gameMode,seed:20260930,objective:kind==='tutorial'?'commander':matchObjective,blueprintA:kind==='tutorial'?undefined:blueRoster,blueprintB:kind==='tutorial'?undefined:redRoster});prepareBattle();save();setScreen('battle');}
function startCampaign(id:string,skipStory=false){const index=CAMPAIGN_MISSIONS.findIndex(m=>m.id===id),mission=getCampaignMission(id);if(!mission||!missionUnlocked(campaignProgress(),index))return;campaignFocus=index;if(!skipStory){openStory(id,'intro','battle');return}mode='ai';mapId=mission.map;state=createGame({map:mission.map,mode:'ai',mission:id,seed:1});prepareBattle();selected=state.units.find(u=>u.team==='blue'&&u.archetype===(mission.lessonSteps[0]?.archetype??mission.introduced))?.id??null;moveCells=selected?legalMoves(state,selected):[];save();setScreen('battle')}
function renderCampaign(){const progress=campaignProgress();if(!missionUnlocked(progress,campaignFocus))campaignFocus=Math.max(0,CAMPAIGN_MISSIONS.findIndex(m=>m.id===nextCampaignMissionId(progress)));app.innerHTML=campaignScreenHTML(progress,campaignFocus);bindCampaignActions();document.querySelector('#campaign-menu')?.addEventListener('click',()=>setScreen('menu'));document.querySelectorAll('[data-mission]').forEach(el=>el.addEventListener('click',()=>{campaignFocus=Number((el as HTMLElement).dataset.mission);renderCampaign()}));document.querySelector('#campaign-start')?.addEventListener('click',e=>startCampaign((e.currentTarget as HTMLElement).dataset.id!));document.querySelector('.mission-start')?.insertAdjacentHTML('beforeend','<button class="btn ghost" id="read-intro">Диалог перед боем</button>'+ (progress.completed.includes(CAMPAIGN_MISSIONS[campaignFocus].id)?'<button class="btn ghost" id="read-outro">После боя</button>':''));document.querySelector('#read-intro')?.addEventListener('click',()=>openStory(CAMPAIGN_MISSIONS[campaignFocus].id,'intro','campaign'));document.querySelector('#read-outro')?.addEventListener('click',()=>openStory(CAMPAIGN_MISSIONS[campaignFocus].id,'outro','campaign'));}
function bindCampaignActions(){
  document.querySelectorAll('[data-campaign-route]').forEach(el=>el.addEventListener('click',()=>{const progress=selectCampaignRoute(campaignProgress(),(el as HTMLElement).dataset.campaignRoute as CampaignRoute);localStorage.setItem('ab-campaign',JSON.stringify(progress));campaignFocus=Math.max(0,CAMPAIGN_MISSIONS.findIndex(m=>m.id===nextCampaignMissionId(progress)));renderCampaign()}));
  document.querySelector('[data-action="campaign-new"]')?.addEventListener('click',()=>{app.insertAdjacentHTML('beforeend',renderNewCampaignConfirmation());document.querySelector('[data-action="campaign-new-cancel"]')?.addEventListener('click',renderCampaign);document.querySelector('[data-action="campaign-new-confirm"]')?.addEventListener('click',()=>{battleEpoch++;clearTimeout(resultTimer);stopMusic();localStorage.setItem('ab-campaign',JSON.stringify(resetCampaignProgress()));localStorage.removeItem('ab-story');try{if(JSON.parse(localStorage.getItem('ab-save')??'null')?.campaignMission)localStorage.removeItem('ab-save')}catch{}state=null;selected=null;modal=null;campaignFocus=0;renderCampaign()})});
}
function openGlobalSettings(){modal='settings';stopMusic();if(screen==='battle')renderBattle();else{app.insertAdjacentHTML('beforeend',modalHTML());bindModal()}}
function languageSelector(){return `<label class="language-picker">Язык / Language <select data-language-select aria-label="Язык / Language"><option value="ru" ${getLanguage()==='ru'?'selected':''}>Русский</option><option value="en" ${getLanguage()==='en'?'selected':''}>English</option></select></label>`}
function rosterNameHTML(){let storedName:string|undefined;try{storedName=JSON.parse(localStorage.getItem('ab-roster')??'null')?.name}catch{}const custom=storedName===roster.name||!PRESETS.some(p=>p.name===roster.name);const name=roster.name.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));return `<span ${custom?'data-user-content':''}>${name}</span>`}
function bindLanguageSelectors(){document.querySelectorAll<HTMLSelectElement>('[data-language-select]').forEach(el=>el.addEventListener('change',()=>{const settingsOpen=modal==='settings';setLanguage(el.value as Language);document.documentElement.lang=getLanguage();document.title=translate('Пепел и знамя');render();if(settingsOpen&&screen!=='battle')openGlobalSettings()}))}
function localizeCanvas(context:CanvasRenderingContext2D){const fill=context.fillText.bind(context),stroke=context.strokeText.bind(context);context.fillText=(value,x,y,maxWidth)=>maxWidth===undefined?fill(translate(value),x,y):fill(translate(value),x,y,maxWidth);context.strokeText=(value,x,y,maxWidth)=>maxWidth===undefined?stroke(translate(value),x,y):stroke(translate(value),x,y,maxWidth)}
function render(){if(screen==='menu')renderMenu();if(screen==='roster')renderRoster();if(screen==='battle')renderBattle();if(screen==='campaign')renderCampaign();if(screen==='howto')renderHowTo();if(screen==='story')renderStory();}
function renderHowTo(){app.innerHTML=howToHTML();for(const id of ['guide-back','guide-back-bottom'])document.querySelector('#'+id)?.addEventListener('click',()=>setScreen('menu'));}
function openStory(id:string,phase:StoryPhase,destination:'battle'|'campaign'){
  const index=CAMPAIGN_MISSIONS.findIndex(m=>m.id===id),progress=campaignProgress();
  if(!missionUnlocked(progress,index)||phase==='outro'&&!progress.completed.includes(id)||phase==='defeat'&&state?.campaignMission!==id)return;
  saveStory(beginStory(storyProgress(),id,phase,destination));storyLog=false;setScreen('story');
}
function resumeStory(){const progress=storyProgress(),cursor=progress.cursor;if(!cursor)return;const index=CAMPAIGN_MISSIONS.findIndex(m=>m.id===cursor.mission);if(!missionUnlocked(campaignProgress(),index)||cursor.phase==='outro'&&!campaignProgress().completed.includes(cursor.mission)){saveStory({...progress,cursor:null});setScreen('campaign');return}storyLog=false;setScreen('story')}
function finishStory(){const progress=storyProgress(),cursor=progress.cursor;if(!cursor||unansweredChoice(progress))return;saveStory(endStory(progress));storyLog=false;if(cursor.destination==='battle')startCampaign(cursor.mission,true);else{campaignFocus=CAMPAIGN_MISSIONS.findIndex(m=>m.id===cursor.mission);modal=null;setScreen('campaign')}}
function advanceStory(){if(storyLog)return;const progress=storyProgress(),cursor=progress.cursor;if(!cursor)return;const scene=storyScene(cursor.mission,cursor.phase,progress.choices,getLanguage())!;if(cursor.index===scene.lines.length-1){finishStory();return}saveStory(stepStory(progress,1));renderStory()}
function renderStory(){const progress=storyProgress(),cursor=progress.cursor;if(!cursor){setScreen('campaign');return}app.innerHTML=storyHTML(progress,reduceMotion,storyLog,getLanguage());if(modal)stopMusic();else startMusic();
  document.querySelector('#story-next')?.addEventListener('click',advanceStory);
  document.querySelector('#story-back')?.addEventListener('click',()=>{saveStory(stepStory(storyProgress(),-1));renderStory()});
  document.querySelector('#story-menu')?.addEventListener('click',()=>setScreen('menu'));
  document.querySelector('#story-settings')?.addEventListener('click',openGlobalSettings);
  document.querySelector('#story-skip')?.addEventListener('click',finishStory);
  for(const id of ['story-log','story-log-close'])document.querySelector('#'+id)?.addEventListener('click',()=>{storyLog=!storyLog;renderStory()});
  document.querySelectorAll('[data-story-choice]').forEach(el=>el.addEventListener('click',()=>{saveStory(chooseStory(storyProgress(),(el as HTMLElement).dataset.storyChoice!));renderStory()}));
  const effect=storyScene(cursor.mission,cursor.phase,progress.choices,getLanguage())!.lines[cursor.index].effect;if(!storyLog&&effect)tone(effect==='bell'?659:effect==='impact'?100:185,effect==='impact'?.24:.6,effect==='impact'?'sawtooth':'sine',.06);
}
function renderMenu(){const saved=localStorage.getItem('ab-save'),stats=JSON.parse(localStorage.getItem('ab-stats')||'{"games":0,"blueWins":0,"redWins":0}');app.innerHTML=`<div class="shell"><div class="grain"></div><section class="screen"><div class="menu-art" style="background-image:url(\'${import.meta.env.BASE_URL}story/menu-v1.png\')"></div><div class="menu"><div class="eyebrow">Тактическая хроника приграничья</div><h1>Пепел<br>и знамя</h1><p>Займите перевалы, удержите сигнальные огни и разбейте вражеский строй. Каждый приказ виден до удара. Каждый уступ меняет бой.</p><div class="menu-actions"><button class="btn primary" id="skirmish">Схватка с ИИ</button><button class="btn" id="hotseat">Локальный PvP</button><button class="btn ghost" id="tutorial">Обучение · 5 минут</button>${saved?'<button class="btn ghost" id="continue">Продолжить</button>':''}</div><p class="tiny" style="margin-top:28px">${touchMode?'Касание: выбор и прогноз · один палец: панорама · два пальца: масштаб · приказ: кнопка подтверждения':'Мышь: выбор и приказ · колесо: масштаб · перетаскивание: панорама · Enter: завершить ход · Esc: пауза'}</p><p class="tiny">Завершено битв: ${stats.games} · побед Лазури: ${stats.blueWins} · побед Ржавчины: ${stats.redWins}</p></div></section></div>`;
document.querySelector('.menu-actions')?.insertAdjacentHTML('afterbegin','<button class="btn primary" id="campaign">Кампания · Огни под пеплом</button>');document.querySelector('#campaign')?.addEventListener('click',()=>{const p=campaignProgress();const first=CAMPAIGN_MISSIONS.findIndex(m=>m.id===nextCampaignMissionId(p));campaignFocus=first<0?(p.route?9:5):first;setScreen('campaign')});if(storyProgress().cursor){document.querySelector('.menu-actions')?.insertAdjacentHTML('beforeend','<button class="btn primary" id="continue-story">Продолжить историю →</button>');document.querySelector('#continue-story')?.addEventListener('click',()=>resumeStory())}
if(localStorage.getItem('ab-last-replay')){document.querySelector('.menu-actions')?.insertAdjacentHTML('beforeend','<button class="btn ghost" id="watch-replay">Последний повтор</button>');document.querySelector('#watch-replay')?.addEventListener('click',()=>{try{const data=JSON.parse(localStorage.getItem('ab-last-replay')!);replayInitial=data.initial;replayCommands=data.history;replayIndex=0;state=replayGame(replayInitial!,[]);prepareBattle();replayMode=true;mapId=state.map.id;mode=state.mode;matchObjective=state.objective.kind;setScreen('battle')}catch(err){console.error(err)}})}
document.querySelector('#skirmish')?.addEventListener('click',()=>{mode='ai';rosterTeam='blue';roster=blueRoster;setScreen('roster')});bindLanguageSelectors();
document.querySelector('.screen')?.insertAdjacentHTML('beforeend','<button class="btn ghost" id="menu-settings">⚙ Настройки</button>');document.querySelector('#menu-settings')?.addEventListener('click',openGlobalSettings);
document.querySelector('#hotseat')?.addEventListener('click',()=>{mode='pvp';rosterTeam='blue';roster=blueRoster;setScreen('roster')});
document.querySelector('#tutorial')?.addEventListener('click',()=>begin('tutorial','ai'));
document.querySelector('.menu-actions')?.insertAdjacentHTML('beforeend','<button class="btn ghost" id="how-to">Как играть · справочник</button>');
document.querySelector('#how-to')?.addEventListener('click',()=>setScreen('howto'));
document.querySelector('#continue')?.addEventListener('click',()=>{try{state=JSON.parse(saved!);mode=state!.mode;mapId=state!.map.id;matchObjective=state!.objective.kind;prepareBattle();modal=state!.winner?'result':null;setScreen('battle');if(!state!.winner&&state!.mode==='ai'&&state!.team==='red')setTimeout(runAI,200)}catch{localStorage.removeItem('ab-save');renderMenu()}});
}
function renderRoster(){const errors=validateBlueprint(roster), total=rosterCost(roster);app.innerHTML=`<div class="roster-screen"><div class="roster-head"><div><div class="eyebrow">Перед битвой · ${mode==='pvp'?(rosterTeam==='blue'?'сторона лазури':'сторона ржавчины'):'схватка против ИИ'}</div><h1 class="serif">Соберите отряд</h1></div><button class="btn ghost" id="back">← Меню</button></div><div class="roster-layout"><div><div class="class-grid">${Object.entries(ARCHETYPES).map(([key,def])=>`<button class="class-card ${draft.archetype===key?'selected':''}" data-class="${key}"><div class="glyph">${GLYPHS[key as Archetype]}</div><h3>${NAMES[key as Archetype]}</h3><p>${def.description}</p><p style="color:#e3c785;margin-top:9px">Стоимость ${def.cost} · движение ${def.move} · урон ${def.damage}</p></button>`).join('')}</div><p class="roster-footer">Отряд: 3–5 бойцов. Не более двух артефактов. Каждая специализация и реликвия меняет правила прямо на поле. Наведите курсор на бойца в матче, чтобы увидеть все его свойства.</p></div><aside class="roster-side"><div class="small-label">Резерв снабжения</div><div class="budget">${total} / ${BUDGET}</div><h2>${NAMES[draft.archetype]}</h2><p class="tip">${ARCHETYPES[draft.archetype].ability}</p><label>Специализация</label><select id="variant">${VARIANTS[draft.archetype].map(v=>`<option value="${v.id}" ${draft.variant===v.id?'selected':''}>${v.name} · +${v.cost} — ${v.description}</option>`).join('')}</select><label>Модификатор</label><select id="modifier"><option value="">Без модификатора</option>${Object.entries(MODIFIERS).map(([id,v])=>`<option value="${id}" ${draft.modifier===id?'selected':''}>${v.name} · +${v.cost} — ${v.description}</option>`).join('')}</select><label>Артефакт</label><select id="artifact"><option value="">Без артефакта</option>${Object.entries(ARTIFACTS).map(([id,v])=>`<option value="${id}" ${draft.artifact===id?'selected':''}>${v.name} · +${v.cost} — ${v.description}</option>`).join('')}</select><button class="btn" id="add">+ Добавить бойца</button><div class="small-label" style="margin-top:20px">Состав: ${rosterNameHTML()}</div>${roster.units.map((u,i)=>`<div class="slot"><span>${GLYPHS[u.archetype]} ${NAMES[u.archetype]} · ${VARIANTS[u.archetype].find(v=>v.id===u.variant)?.name??'основной'} <small style="color:#d6bd81">${u.artifact?'✦':''}</small></span><button data-remove="${i}" title="Убрать">✕</button></div>`).join('')}${errors.map(e=>`<p style="color:#e7a28d;font-size:11px">${e}</p>`).join('')}<button class="btn primary" id="start" ${errors.length?'disabled':''}>${mode==='pvp'&&rosterTeam==='blue'?'Выбрать отряд второй стороны':'Начать битву →'}</button><button class="btn ghost" id="save-roster">Сохранить состав</button><button class="btn ghost" id="load-roster">Загрузить свой</button><label>Готовые составы</label><select id="preset"><option value="-1">Выберите пресет</option>${PRESETS.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('')}</select></aside></div></div>`;
const totals=getUnitRules(draft as Unit);document.querySelector('.roster-side h2')?.insertAdjacentHTML('afterend',`<div class="statline"><span>♥ ${totals.hp}</span><span>↗ ${totals.move}</span><span>⚔ ${totals.damage}</span><span>◎ ${totals.minRange}–${totals.range}</span><span>◈ ${choiceCost(draft)}</span></div>`);
document.querySelector('.roster-head')?.insertAdjacentHTML('beforeend',`<button class="btn primary" id="start-top" ${errors.length?'disabled':''}>${mode==='pvp'&&rosterTeam==='blue'?'Выбрать второй отряд':'Начать битву →'}</button>`);
for(const [id,description] of [['variant',VARIANTS[draft.archetype].find(v=>v.id===draft.variant)?.description],['modifier',draft.modifier?(MODIFIERS as any)[draft.modifier]?.description:undefined],['artifact',draft.artifact?(ARTIFACTS as any)[draft.artifact]?.description:undefined]] as const){const select=document.querySelector('#'+id);if(select&&description)select.insertAdjacentHTML('afterend',`<p class="tip">${description}</p>`)}
if(mode==='ai'){const start=document.querySelector('#start');start?.insertAdjacentHTML('beforebegin',`<label>Сложность ИИ</label><select id="difficulty"><option value="easy" ${aiDifficulty==='easy'?'selected':''}>Дозор · спокойный</option><option value="normal" ${aiDifficulty==='normal'?'selected':''}>Дружина · обычный</option><option value="hard" ${aiDifficulty==='hard'?'selected':''}>Воевода · глубокий поиск</option></select>`);document.querySelector('#difficulty')?.addEventListener('change',e=>{aiDifficulty=(e.target as HTMLSelectElement).value as Difficulty;localStorage.setItem('ab-difficulty',aiDifficulty)})}
document.querySelector('#start-top')?.insertAdjacentHTML('beforebegin',`<div class="roster-goal"><label for="match-objective">Цель матча</label><select id="match-objective" ${mode==='pvp'&&rosterTeam==='red'?'disabled':''}><option value="control" ${matchObjective==='control'?'selected':''}>Контроль сигнальных огней</option><option value="commander" ${matchObjective==='commander'?'selected':''}>Победить командира</option><option value="elimination" ${matchObjective==='elimination'?'selected':''}>Победить всех бойцов</option></select><small>${mode==='pvp'&&rosterTeam==='red'?'Выбрала первая сторона · ':''}${matchObjective==='control'?'Удерживайте две точки до 5 очков.':matchObjective==='commander'?'Выведите из боя вражеского командира.':'Выведите из боя весь вражеский отряд.'}</small></div>`);
document.querySelector('#match-objective')?.addEventListener('change',e=>{matchObjective=(e.target as HTMLSelectElement).value as GameState['objective']['kind'];localStorage.setItem('ab-objective',matchObjective);renderRoster()});
document.querySelector('#back')?.addEventListener('click',()=>setScreen('menu'));
document.querySelectorAll('[data-class]').forEach(el=>el.addEventListener('click',()=>{draft={archetype:(el as HTMLElement).dataset.class as Archetype,variant:VARIANTS[(el as HTMLElement).dataset.class as Archetype][0].id};renderRoster()}));
for(const id of ['variant','modifier','artifact'])document.querySelector('#'+id)?.addEventListener('change',e=>{const val=(e.target as HTMLSelectElement).value;(draft as any)[id]=val||undefined;renderRoster()});
document.querySelector('#add')?.addEventListener('click',()=>{const next={...roster,units:[...roster.units,clone(draft)]};if(validateBlueprint(next).some(e=>e.includes('превышен')||e.includes('более')||e.includes('несовмест')||e.includes('доступен')||e.includes('не несёт')))tone(140,.2,'sawtooth');else{roster=next;tone(560);renderRoster()}});
document.querySelectorAll('[data-remove]').forEach(el=>el.addEventListener('click',()=>{roster={...roster,units:roster.units.filter((_,i)=>i!==Number((el as HTMLElement).dataset.remove))};renderRoster()}));
document.querySelector('#preset')?.addEventListener('change',e=>{const i=Number((e.target as HTMLSelectElement).value);if(i>=0){roster=clone(PRESETS[i]);renderRoster()}});
document.querySelector('#save-roster')?.addEventListener('click',()=>{const name=prompt(translate('Название отряда'),roster.name);if(name){roster.name=name.slice(0,40);localStorage.setItem('ab-roster',JSON.stringify(roster));renderRoster()}});
document.querySelector('#load-roster')?.addEventListener('click',()=>{try{const b=JSON.parse(localStorage.getItem('ab-roster')||'null');if(b){roster=b;renderRoster()}}catch{}});
document.querySelector('#start')?.addEventListener('click',()=>{if(rosterTeam==='blue'){blueRoster=clone(roster);if(mode==='pvp'){rosterTeam='red';roster=redRoster;renderRoster();return}}else redRoster=clone(roster);begin('highland',mode)});
document.querySelector('#start-top')?.addEventListener('click',()=>document.querySelector<HTMLButtonElement>('#start')?.click());
}
function renderBattle(){if(!state)return;cancelAnimationFrame(raf);app.innerHTML=`<div class="shell ${inspectorOpen?'inspector-open':''}"><div class="battle"><canvas id="board"></canvas><div class="hud-left"><div class="panel" id="selection-panel"></div><div class="panel" id="units-panel"></div></div><div class="hud-right"><div class="panel" id="objective-panel"></div><div class="panel preview" id="preview-panel"></div><div class="panel" id="log-panel"></div></div><div class="bottom-help" id="help"></div></div><div class="topbar"><div class="brand">Пепел и знамя<small>${state.map.name}</small></div><div class="top-mid"><span class="turn-pill ${state.team}">Ход ${state.turn} · ${state.team==='blue'?'Лазурь':'Ржавчина'}</span><span>${state.campaignMission?'Кампания':state.mode==='ai'?'Схватка с ИИ':'Локальный PvP'}</span></div><div class="top-actions"><button class="btn ghost inspector-toggle" id="inspect-toggle" aria-expanded="${inspectorOpen}" aria-controls="selection-panel">Отряд</button><button class="btn ghost" id="undo">Отменить шаг</button><button class="btn primary" id="end-turn">Завершить ход ↵</button><button class="btn ghost" id="pause">Ⅱ</button></div></div>${modal?modalHTML():''}</div>`;
if(replayMode)document.querySelector('.top-actions')!.innerHTML=`<button class="btn ghost" id="replay-prev">← Назад</button><span class="turn-pill">${replayIndex} / ${replayCommands.length}</span><button class="btn primary" id="replay-next">Далее →</button><button class="btn ghost" id="replay-exit">В меню</button>`;
canvas=document.querySelector<HTMLCanvasElement>('#board')!;ctx=canvas.getContext('2d')!;localizeCanvas(ctx);bindCanvas();bindTabletButtons();updateHUD();frame();if(modal)stopMusic();else startMusic();
document.querySelector('#inspect-toggle')?.addEventListener('click',()=>{inspectorOpen=!inspectorOpen;document.querySelector('.shell')?.classList.toggle('inspector-open',inspectorOpen);document.querySelector('#inspect-toggle')?.setAttribute('aria-expanded',String(inspectorOpen))});
document.querySelector('#undo')?.addEventListener('click',doUndo);document.querySelector('#end-turn')?.addEventListener('click',endPlayerTurn);document.querySelector('#pause')?.addEventListener('click',()=>{modal='pause';renderBattle()});bindModal();
if(!replayMode&&state.mode==='ai'&&state.team==='red'&&!state.winner&&!modal)setTimeout(runAI,200/animationSpeed);
document.querySelector('#replay-prev')?.addEventListener('click',()=>replayStep(-1));document.querySelector('#replay-next')?.addEventListener('click',()=>replayStep(1));document.querySelector('#replay-exit')?.addEventListener('click',()=>{replayMode=false;setScreen('menu')});
}
function replayStep(delta:number){if(!replayInitial)return;motions.clear();const before=state;replayIndex=Math.max(0,Math.min(replayCommands.length,replayIndex+delta));state=replayGame(replayInitial,replayCommands.slice(0,replayIndex));resetSpriteAnimations();if(delta>0&&before){recordSpriteCommand(before,state);noteDamage(before,state)}else damageNumbers.length=0;selected=null;preview=null;moveCells=[];renderBattle()}
function modalHTML(){if(modal==='pause')return `<div class="modal-back"><div class="modal"><div class="eyebrow">Передышка</div><h1>Пауза</h1><p>Партия сохранена на этом устройстве.</p><div class="menu-actions"><button class="btn primary" data-modal="resume">Продолжить</button><button class="btn" data-modal="restart">Начать заново</button><button class="btn" data-modal="settings">Настройки</button><button class="btn ghost" data-modal="menu">В меню</button></div></div></div>`;
if(modal==='settings')return `<div class="modal-back"><div class="modal"><h1>Настройки</h1>${languageSelector()}<p>Звуки <span id="volume-num">${Math.round(soundVolume*100)}%</span></p><input id="volume" type="range" min="0" max="1" step=".05" value="${soundVolume}" style="width:100%"><p>Музыка <span id="music-volume-num">${Math.round(musicVolume*100)}%</span></p><input id="music-volume" type="range" min="0" max="1" step=".05" value="${musicVolume}" style="width:100%"><p>Скорость анимаций</p><select id="speed" style="padding:10px;background:#31483b;color:white"><option value=".6" ${animationSpeed===.6?'selected':''}>Спокойно</option><option value="1" ${animationSpeed===1?'selected':''}>Обычно</option><option value="1.8" ${animationSpeed===1.8?'selected':''}>Быстро</option></select><label class="settings-toggle"><input id="contrast" type="checkbox" ${highContrast?'checked':''}> Высокий контраст</label><label class="settings-toggle"><input id="reduce-motion" type="checkbox" ${reduceMotion?'checked':''}> Без анимации движения</label><div class="menu-actions"><button class="btn primary" data-modal="pause">Готово</button></div></div></div>`;
if(state?.campaignMission)return campaignResultHTML(state,campaignProgress());
const won=state?.winner==='blue';return `<div class="modal-back"><div class="modal"><div class="eyebrow">Хроника перевала</div><h1>${won?'Победа':'Битва окончена'}</h1><p>${state?.winner==='draw'?`Ничья после ${state.turn} раундов.`:`Победила сторона ${won?'Лазури':'Ржавчины'}. Ходов: ${state?.turn}.`}</p><div class="menu-actions"><button class="btn primary" data-modal="restart">Новый бой</button><button class="btn ghost" data-modal="menu">В меню</button></div></div></div>`}
function bindModal(){bindLanguageSelectors();document.querySelectorAll('[data-modal]').forEach(el=>el.addEventListener('click',()=>{const v=(el as HTMLElement).dataset.modal;if(v==='resume'){modal=null;renderBattle()}if(v==='pause'){if(screen!=='battle'){modal=null;render()}else{modal='pause';renderBattle()}}if(v==='settings'){modal='settings';renderBattle()}if(v==='restart'){if(state?.campaignMission)startCampaign(state.campaignMission);else begin(mapId,mode)}if(v==='campaign-story'&&state?.campaignMission)openStory(state.campaignMission,state.winner==='blue'?'outro':'defeat','campaign');if(v==='campaign-next'){campaignFocus=CAMPAIGN_MISSIONS.findIndex(m=>m.id===(el as HTMLElement).dataset.id);modal=null;setScreen('campaign')}if(v==='campaign'){modal=null;setScreen('campaign')}if(v==='menu'){modal=null;setScreen('menu')}}));document.querySelector('#volume')?.addEventListener('input',e=>{soundVolume=Number((e.target as HTMLInputElement).value);localStorage.setItem('ab-volume',String(soundVolume));document.querySelector('#volume-num')!.textContent=Math.round(soundVolume*100)+'%'});document.querySelector('#music-volume')?.addEventListener('input',e=>{musicVolume=Number((e.target as HTMLInputElement).value);localStorage.setItem('ab-music-volume',String(musicVolume));document.querySelector('#music-volume-num')!.textContent=Math.round(musicVolume*100)+'%'});document.querySelector('#speed')?.addEventListener('change',e=>{animationSpeed=Number((e.target as HTMLSelectElement).value);localStorage.setItem('ab-speed',String(animationSpeed))});document.querySelector('#contrast')?.addEventListener('change',e=>{highContrast=(e.target as HTMLInputElement).checked;localStorage.setItem('ab-contrast',highContrast?'1':'0');document.documentElement.classList.toggle('high-contrast',highContrast)});document.querySelector('#reduce-motion')?.addEventListener('change',e=>{reduceMotion=(e.target as HTMLInputElement).checked;localStorage.setItem('ab-reduce-motion',reduceMotion?'1':'0');if(reduceMotion)motions.clear()})}
function updateHUD(){if(!state||screen!=='battle')return;if(touchOrder&&(touchOrder.state!==state||!playerCanAct()||touchOrder.command.type==='endTurn'||touchOrder.command.unitId!==selected||touchOrder.mode!==actionMode))touchOrder=null;const u=chosen(),tile=hovered?tileAt(hovered.x,hovered.y):null,hoverUnit=hovered?unitAt(hovered.x,hovered.y):null;
const sp=document.querySelector('#selection-panel');if(sp)sp.innerHTML=u?`<div class="small-label">${u.team==='blue'?'Лазурь':'Ржавчина'} · ${u.id}</div><h2>${GLYPHS[u.archetype]} ${campaignUnitName(u)??NAMES[u.archetype]} ${u.commander?'♛':''}</h2><div class="hpbar"><i style="width:${Math.max(0,u.hp/u.maxHp*100)}%"></i></div><div class="statline"><span>Здоровье <b>${u.hp}/${u.maxHp}</b></span><span>Высота <b>${tileAt(u.x,u.y)?.h??0}</b></span></div><div class="statline"><span>Движение <b>${u.moved?'исп.':getRulesMove(u)}</b></span><span>Атака <b>${u.acted?'исп.':ARCHETYPES[u.archetype].damage}</b></span></div><div class="abilities"><button class="ability ${actionMode==='attack'?'active':''}" data-action="attack" ${!u.alive||u.acted||!isMine(u)?'disabled':''}>⚔ Атака</button><button class="ability ${actionMode==='ability'?'active':''}" data-action="ability" ${!u.alive||u.acted||!isMine(u)?'disabled':''}>✦ Приём</button></div><div class="tip">${u.pinned?'<b>Остановлен: шаг и рывок запрещены до конца вашего хода.</b><br>':''}${ARCHETYPES[u.archetype].description}<br><b style="color:#e6c789">Приём:</b> ${ARCHETYPES[u.archetype].ability}</div><div style="margin-top:8px">${u.variant?`<span class="rule-tag" title="${VARIANTS[u.archetype].find(v=>v.id===u.variant)?.description??''}">${VARIANTS[u.archetype].find(v=>v.id===u.variant)?.name??u.variant}</span>`:''}${u.modifier?`<span class="rule-tag" title="${(MODIFIERS as any)[u.modifier]?.description??''}">${(MODIFIERS as any)[u.modifier]?.name??u.modifier}</span>`:''}${u.artifact?`<span class="rule-tag" title="${(ARTIFACTS as any)[u.artifact]?.description??''}">✦ ${(ARTIFACTS as any)[u.artifact]?.name??u.artifact}</span>`:''}</div>`:`<div class="small-label">Приказы</div><h2>Выберите бойца</h2><p class="tip">Нажмите на своего бойца. Голубые клетки показывают возможное движение; наведите на врага для точного прогноза атаки.</p>`;
if(u?.archetype==='sword'&&sp){const button=sp.querySelector('[data-action="ability"]');if(button)button.textContent='✦ Толчок / стража'}
if(u?.guard&&sp)sp.insertAdjacentHTML('afterbegin',`<div class="stance-indicator">⬡ Стража: −1 урон${u.archetype==='sword'?' · ответ 1':''}</div>`);
if(u&&state.objective.protectedIds?.includes(u.id)&&sp)sp.insertAdjacentHTML('afterbegin',`<div class="stance-indicator">◇ Защищаемый боец · ${u.evacuated?'выведен живым':state.objective.kind==='defend'?'сохраните до конца обороны':'ведите к зелёному выходу'}</div>`);
if(touchMode&&sp)sp.querySelectorAll<HTMLElement>('.rule-tag').forEach(tag=>{tag.setAttribute('role','button');tag.tabIndex=0;const explain=()=>{sp.querySelector('.rule-detail')?.remove();const detail=document.createElement('p');detail.className='tip rule-detail';detail.textContent=tag.title;sp.append(detail)};tag.addEventListener('click',explain);tag.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();explain()}})});
document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>{actionMode=(el as HTMLElement).dataset.action as any;updatePreview();updateHUD();tone(480)}));
const up=document.querySelector('#units-panel');if(up)up.innerHTML=`<div class="small-label">Порядок действий свободный</div><h3>Отряды</h3><div class="mini-list">${state.units.map(v=>`<div class="unit-row ${v.id===selected?'selected':''} ${!v.alive&&!v.evacuated?'dead':''}" data-unit="${v.id}"><span><i class="badge ${v.team}"></i>${GLYPHS[v.archetype]} ${campaignUnitName(v)??NAMES[v.archetype]}${state!.objective.protectedIds?.includes(v.id)?' ◇':''}${v.artifact?' ✦':''}</span><span>${v.evacuated?'✓ Вышел':v.hp+'♥ '+(v.acted?'✓':'')}</span></div>`).join('')}</div>`;
document.querySelectorAll('[data-unit]').forEach(el=>el.addEventListener('click',()=>{const id=(el as HTMLElement).dataset.unit!;const v=state!.units.find(x=>x.id===id);if(v?.alive){selected=id;actionMode='attack';moveCells=isMine(v)?legalMoves(state!,v.id):[];updatePreview();updateHUD();tone(520)}}));
const op=document.querySelector('#objective-panel');if(op)op.innerHTML=state.map.id==='tutorial'?`<div class="small-label">Полевые учения</div><h3>${tutorialHint().title}</h3><div class="tip">${tutorialHint().text}</div><div class="statline"><span>Цель: победить командира ♛</span></div>`:state.objective.kind==='control'?`<div class="small-label">Цель боя</div><h3>Удержать сигнальные огни</h3><div class="tip">Удерживайте две из четырёх точек в конце полного раунда. Серия до ${state.objective.target} очков сбрасывается при потере контроля.</div><div class="statline"><span class="objective">Лазурь: ${state.objective.scores.blue}</span><span class="threat">Ржавчина: ${state.objective.scores.red}</span><span>Цель: ${state.objective.target}</span></div>`:state.objective.kind==='commander'?`<div class="small-label">Цель боя</div><h3>Победить командира</h3><div class="tip">Выведите из боя вражеского командира ♛. До конца 12-го раунда, если никто не достиг цели, решают выжившие и здоровье.</div><div class="statline"><span>Лазурь: ${state.units.find(v=>v.team==='blue'&&v.commander&&v.alive)?.hp??0} ♛</span><span>Ржавчина: ${state.units.find(v=>v.team==='red'&&v.commander&&v.alive)?.hp??0} ♛</span></div>`:`<div class="small-label">Цель боя</div><h3>Победить всех бойцов</h3><div class="tip">Выведите из боя весь вражеский отряд. До конца 12-го раунда решают выжившие и здоровье.</div><div class="statline"><span>Лазурь: ${state.units.filter(v=>v.team==='blue'&&v.alive).length} бойцов</span><span>Ржавчина: ${state.units.filter(v=>v.team==='red'&&v.alive).length} бойцов</span></div>`;
if(state.map.id==='tutorial'){const targetLabel=op?.querySelector('.statline span');if(targetLabel)targetLabel.textContent='Цель: победить командира Ржавчины ♛'}
else if(state.objective.kind==='control'){const tip=op?.querySelector('.tip');if(tip)tip.textContent=`Удерживайте ${Math.min(2,state.objective.points.length)} из ${state.objective.points.length} точек в конце полного раунда. Серия до ${state.objective.target} очков сбрасывается, если контроль потерян.`}
if(state.campaignMission&&op){const special=scenarioObjectiveHTML(state);if(special)op.innerHTML=special;const tip=op.querySelector('.tip');if(tip&&!special){if(state.objective.kind==='control')tip.textContent+=` Цель за 12 раундов.`;else tip.textContent=state.objective.kind==='commander'?'Победите командира ♛ за 12 раундов. Защитите своего командира.':'Победите весь вражеский отряд за 12 раундов.'}op.insertAdjacentHTML('beforeend',campaignLessonHTML(state))}
const pp=document.querySelector('#preview-panel');if(pp){const p=preview;let title=touchMode?'Выбор цели':'Наведение',detail=touchMode?'Коснитесь доступной клетки или цели.':'Наведите на доступную клетку или цель.';let cls='';if(p){title=p.valid?(p.type==='move'?'Маршрут':p.type==='ability'?'Приём':'Атака'):'Приказ недоступен';detail=p.valid?`${p.cost!=null?`Стоимость ${p.cost}. `:''}${p.damage!=null?`Урон ${p.damage}. `:''}${p.counterDamage?`Ответ ${p.counterDamage}. `:''}${p.push?`Отбрасывание → ${p.push.x},${p.push.y}. `:''}${p.fallDamage?`Падение ${p.fallDamage}. `:''}${p.hazardDamage?`Опасность ${p.hazardDamage}. `:''}${p.killed?'Цель погибнет. ':''}${p.explanation??''}`:p.reason??'Нет допустимого действия';if(p.valid&&p.targetId)detail+=' '+combatFactors(p);if(p.valid&&p.type==='move'&&p.to&&moveCells.find(c=>c.x===p.to!.x&&c.y===p.to!.y)?.threatened)detail+=' ⚠ Под ударом врага на следующем ходу.';cls=p.valid?'good':'bad'}pp.className='panel preview '+cls;pp.innerHTML=`<div class="small-label">Точный прогноз до подтверждения</div><div class="big">${title}</div><div class="tip">${detail}</div>`; }
if(preview?.valid&&preview.objectDamage!=null&&preview.objectDamage>0&&pp){const change=preview.tileChange;pp.insertAdjacentHTML('beforeend',`<div class="tip" style="color:#f1cd8e;margin-top:9px">Объект: −${preview.objectDamage} прочности.${change?` После удара: ${TERRAIN[change.terrain]??change.terrain}${change.hp?` · ${change.hp} прочности`:''}.`:''}${preview.killed?' Боец на мосту погибнет.':''}</div>`)}
const lp=document.querySelector('#log-panel');if(lp)lp.innerHTML=`<div class="small-label">Хроника</div><div class="log">${state.log.slice(-7).reverse().map(e=>`<div>◦ ${prettyLog(e.message)}</div>`).join('')}</div>`;
if(preview?.valid&&preview.objectiveProgress&&pp)pp.insertAdjacentHTML('beforeend',`<div class="tip objective" style="margin-top:9px">◇ Боец покинет поле живым. Отменить выход нельзя.${preview.objectiveProgress.wins?' Задача будет выполнена.':''}</div>`);
const help=document.querySelector('#help');if(help)help.innerHTML=tile?`<strong>${tile.x+1}:${tile.y+1}</strong> · высота <strong>${tile.h}</strong> · ${TERRAIN[tile.terrain]??tile.terrain}${tile.object?' · '+objectName(tile.object):''}${hoverUnit?' · '+NAMES[hoverUnit.archetype]+' '+hoverUnit.hp+'♥':''}${tile.object==='fragile'?' · Shift+ЛКМ: сломать мост':''} &nbsp; | &nbsp; ЛКМ: приказ · ПКМ: отмена выбора · колесо: масштаб · перетаскивание: карта`:'ЛКМ: выбор и приказ · ПКМ: отмена выбора · колесо: масштаб · перетаскивание: карта · Enter: завершить ход';
if(help&&tile&&tileHazardDamage(tile))help.insertAdjacentHTML('beforeend',` · ${tileHazardDamage(tile)} урона при остановке`);
if(help&&tile?.hp)help.insertAdjacentHTML('beforeend',` · прочность ${tile.hp}`);
if(help&&tile&&state.objective.exits?.some(p=>p.x===tile.x&&p.y===tile.y))help.insertAdjacentHTML('beforeend',' · ↗ Выход: отмеченные бойцы покидают поле живыми');
if(help)help.insertAdjacentHTML('beforeend',' · H: все высоты');
const undo=document.querySelector<HTMLButtonElement>('#undo');if(undo)undo.disabled=!playerCanAct()||!u||!previewAction(state,{type:'undo',unitId:u.id,x:u.x,y:u.y}).valid;
const end=document.querySelector<HTMLButtonElement>('#end-turn');if(end)end.disabled=!playerCanAct();updateTabletButtons();
}
function getRulesMove(u:Unit){return getUnitRules(u).move}
function objectName(id:string){if(id==='objective'&&state?.objective.kind==='defend')return 'хранилище: не допустить врага к концу его хода';if(id==='objective'&&state?.objective.kind!=='control')return 'неактивный сигнальный пост';return ({cover:'укрытие',brazier:'костёр',trap:'ловушка',objective:'сигнальный огонь',fragile:'хрупкий мост'} as any)[id]??id}
function prettyLog(message:string){return message.replace(/(blue|red)-(\d+)/g,(_,team,index)=>{const u=state?.units.find(v=>v.id===team+'-'+index);return u?`${NAMES[u.archetype]} ${team==='blue'?'Лазури':'Ржавчины'}`:team+'-'+index})}
function combatFactors(p:Preview){const a=chosen(),t=state?.units.find(v=>v.id===p.targetId);if(!a||!t)return'';const ah=tileAt(a.x,a.y)?.h??0,th=tileAt(t.x,t.y)?.h??0;const notes:string[]=[];if(ah>th)notes.push('позиция сверху +1');if(a.archetype==='archer'&&th>ah)notes.push('выстрел снизу −1');if(t.guard)notes.push('стража цели −1');if(state?.units.some(v=>v.alive&&v.team===t.team&&v.archetype==='shield'&&Math.abs(v.x-t.x)+Math.abs(v.y-t.y)===1))notes.push('щит союзника −1');return notes.length?'Расчёт: '+notes.join(', ')+'.':''}
function tutorialHint(){if(!state)return {title:'Выберите бойца',text:'Нажмите на своего бойца.'};const actions=state.history.filter(c=>c.type!=='endTurn');if(!selected&&actions.length===0)return {title:'1 / 4 · Выберите бойца',text:'Нажмите на одного из трёх бойцов Лазури. Порядок их действий выбираете вы.'};if(!actions.some(c=>c.type==='move'))return {title:'2 / 4 · Займите позицию',text:'Голубые клетки показывают доступный маршрут. Подъём стоит дополнительное движение; лестница позволяет подняться выше.'};if(!actions.some(c=>c.type==='attack'||c.type==='ability'))return {title:'3 / 4 · Рассчитайте удар',text:'Выберите другого бойца или наведите на врага. Панель прогноза покажет урон, отбрасывание и блокировку обзора до клика.'};if(state.turn===1)return {title:'4 / 4 · Передайте ход',text:'Неиспользованный боец ещё может действовать. Когда закончите, нажмите «Завершить ход»; затем ответит враг. Цель — командир Ржавчины ♛.'};return {title:'Учения продолжаются',text:'Используйте высоту, берегите лучника в ближнем бою и бейте копьём по прямой через союзника. Победите командира Ржавчины ♛.'}}
function updatePreview(){if(!state||!selected||!hovered){preview=null;return}const u=chosen();if(!u||!isMine(u)){preview=null;return}const target=unitAt(hovered.x,hovered.y),object=tileAt(hovered.x,hovered.y)?.object;let type:Command['type']=actionMode==='ability'&&(!target||target.team!==u.team||target.id===u.id||reinforcing(u,tileAt(hovered.x,hovered.y)))?'ability':target&&target.team!==u.team||actionMode==='attack'&&(object==='cover'||object==='fragile'&&shiftHeld)?'attack':'move';if(target&&target.team===u.team&&!(type==='ability'&&(target.id===u.id||reinforcing(u,tileAt(hovered.x,hovered.y))))){preview=null;return}try{preview=previewAction(state,{type,unitId:u.id,x:hovered.x,y:hovered.y} as Command)}catch{preview=null}}
function doUndo(){if(!state||!selected||!playerCanAct())return;try{const before=state;state=undoMove(state,selected);queueMotion(before,state);moveCells=legalMoves(state,selected);preview=null;save();updateHUD();tone(250)}catch{}}
function commit(cmd:Command){if(!state||!playerCanAct())return;let before=state;try{const p=previewAction(state,cmd);if(!p.valid){tone(130,.18,'sawtooth');return}state=applyAction(state,cmd);queueMotion(before,state,p.path,'unitId'in cmd?cmd.unitId:undefined);noteDamage(before,state);activePulse={x:'x'in cmd?cmd.x:0,y:'y'in cmd?cmd.y:0,kind:cmd.type,at:performance.now()};tone(cmd.type==='move'?400:cmd.type==='attack'?175:650,cmd.type==='move'?.07:.18,cmd.type==='attack'?'sawtooth':'triangle');if(cmd.type==='attack'||cmd.type==='ability')actionMode='attack';if(selected)moveCells=legalMoves(state,selected);save();if(state.winner){finishMatch();return}updatePreview();updateHUD()}catch(err){state=before;console.warn(err);tone(130,.2,'sawtooth')}}
function motionPoint(x:number,y:number,map:GameState['map']):MotionPoint{return{x,y,h:map.tiles.find(t=>t.x===x&&t.y===y)?.h??0}}
function sampleMotion(m:Motion,now=performance.now()):MotionPoint{const progress=Math.max(0,Math.min(1,(now-m.at)/m.duration));const eased=progress*progress*(3-2*progress),along=eased*(m.points.length-1),leg=Math.min(m.points.length-2,Math.floor(along)),t=along-leg,a=m.points[leg],b=m.points[leg+1];return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,h:a.h+(b.h-a.h)*t}}
function queueMotion(before:GameState,after:GameState,path?:{x:number;y:number}[],moverId?:string){recordSpriteCommand(before,after);if(reduceMotion)return;const now=performance.now();for(const old of before.units){const next=after.units.find(v=>v.id===old.id);if(!next||old.x===next.x&&old.y===next.y)continue;const existing=motions.get(old.id);const start=existing&&now<existing.at+existing.duration?sampleMotion(existing,now):motionPoint(old.x,old.y,before.map);const route=old.id===moverId&&path?.length?path:[{x:next.x,y:next.y}];const points=[start,...route.map(c=>motionPoint(c.x,c.y,after.map))];const distance=points.slice(1).reduce((sum,p,i)=>sum+Math.hypot(p.x-points[i].x,p.y-points[i].y),0);motions.set(old.id,{points,at:now,duration:Math.max(110,Math.round(180*distance/animationSpeed))})}}
function finishMatch(){if(!state)return;const stat=JSON.parse(localStorage.getItem('ab-stats')||'{"games":0,"blueWins":0,"redWins":0}');stat.games++;if(state.winner==='blue')stat.blueWins++;if(state.winner==='red')stat.redWins++;localStorage.setItem('ab-stats',JSON.stringify(stat));localStorage.setItem('ab-last-replay',JSON.stringify({initial:state.initial,history:state.history,log:state.log}));if(state.campaignMission&&state.winner==='blue')localStorage.setItem('ab-campaign',JSON.stringify(recordCampaignVictory(campaignProgress(),state.campaignMission)));const finished=state;updateHUD();const latest=Math.max(performance.now()-650,...damageNumbers.map(d=>d.at));resultTimer=setTimeout(()=>{if(screen==='battle'&&state===finished){modal='result';renderBattle();tone(state.winner==='blue'?630:250,.5,'triangle')}},Math.max(0,latest+650-performance.now()))}
function endPlayerTurn(){if(!state||!playerCanAct())return;try{state=applyAction(state,{type:'endTurn'});selected=null;preview=null;moveCells=[];save();tone(360,.22,'triangle');if(state.winner){finishMatch();return}renderBattle();if(state.mode==='ai'&&state.team==='red')setTimeout(runAI,200/animationSpeed)}catch(err){console.error(err)}}
async function runAI(){
  if(!state||replayMode||screen!=='battle'||state.mode!=='ai'||state.team!=='red'||state.winner||modal||runningAiEpoch===battleEpoch)return;
  const epoch=battleEpoch;runningAiEpoch=epoch;
  const current=()=>epoch===battleEpoch&&screen==='battle'&&!modal&&!replayMode&&state?.mode==='ai'&&state.team==='red';
  try{
    for(let i=0;i<18&&current()&&!state!.winner;i++){
      const cmd=chooseAiCommand(state!,state!.campaignMission?'easy':aiDifficulty);
      if(!cmd||cmd.type==='endTurn'){state=applyAction(state!,{type:'endTurn'});break}
      const p=previewAction(state!,cmd);if(!p.valid)break;
      const before=state!;state=applyAction(state!,cmd);queueMotion(before,state,p.path,cmd.unitId);noteDamage(before,state);
      activePulse={x:'x'in cmd?cmd.x:0,y:'y'in cmd?cmd.y:0,kind:cmd.type,at:performance.now()};tone(cmd.type==='move'?310:165,.1,'triangle');save();updateHUD();
      const motion=motions.get(cmd.unitId);await new Promise(r=>setTimeout(r,reduceMotion?70:Math.max(100,motion?.duration??230/animationSpeed)));
    }
    if(epoch!==battleEpoch||screen!=='battle'||modal||replayMode)return;
    if(current()&&!state!.winner)state=applyAction(state!,{type:'endTurn'});
    save();if(state?.winner){finishMatch();return}renderBattle();
  }catch(err){console.warn('AI order',err)}
  finally{if(runningAiEpoch===epoch)runningAiEpoch=null;if(epoch===battleEpoch&&screen==='battle'&&!modal&&state?.team==='red'&&!state.winner)setTimeout(runAI,200/animationSpeed)}
}
function bindCanvas(){const resize=()=>{if(!canvas?.isConnected)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)};resize();window.onresize=()=>{camera=battleCamera();touchOrder=null;hovered=null;preview=null;resize();updateHUD()};
bindTouchControls(canvas,{activate:()=>{touchMode=true;document.documentElement.classList.add('touch-input')},gesture:()=>{touchOrder=null;hovered=null;preview=null;updateHUD()},tap:tabletTap,pan:(dx,dy)=>{camera.x+=dx;camera.y+=dy},zoom:zoomBoard});
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect(),changed=e.shiftKey!==shiftHeld;shiftHeld=e.shiftKey;mouse={x:e.clientX-r.left,y:e.clientY-r.top};if(drag?.down){camera.x=drag.ox+(mouse.x-drag.x);camera.y=drag.oy+(mouse.y-drag.y);return}const h=pick(mouse.x,mouse.y,e.altKey);if(changed||h?.x!==hovered?.x||h?.y!==hovered?.y){hovered=h;updatePreview();updateHUD()}});
canvas.addEventListener('mousedown',e=>{if(e.button!==0)return;drag={x:e.offsetX,y:e.offsetY,ox:camera.x,oy:camera.y,down:true}});
canvas.addEventListener('mouseup',e=>{if(!drag)return;shiftHeld=e.shiftKey;const distance=Math.hypot(e.offsetX-drag.x,e.offsetY-drag.y);drag=null;if(distance<6){hovered=pick(e.offsetX,e.offsetY,e.altKey);updatePreview();boardClick()}});
canvas.addEventListener('mouseleave',()=>{drag=null;hovered=null;preview=null;updateHUD()});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();selected=null;preview=null;moveCells=[];updateHUD()});
canvas.addEventListener('wheel',e=>{e.preventDefault();const old=camera.zoom;camera.zoom=Math.max(.52,Math.min(2.4,camera.zoom*(e.deltaY<0?1.12:.89)));const ratio=camera.zoom/old;camera.x=e.offsetX-(e.offsetX-camera.x-canvas.clientWidth/2)*ratio-canvas.clientWidth/2;camera.y=e.offsetY-(e.offsetY-camera.y-canvas.clientHeight*.48)*ratio-canvas.clientHeight*.48},{passive:false})}
function boardClick(){if(replayMode||!state||modal||!hovered||state.mode==='ai'&&state.team==='red')return;const u=unitAt(hovered.x,hovered.y);if(u&&u.team===state.team&&!(reinforcing(chosen(),tileAt(hovered.x,hovered.y))&&chosen()&&isMine(chosen()!))){if(selected===u.id&&actionMode==='ability'){commit({type:'ability',unitId:u.id,x:u.x,y:u.y});return}selected=u.id;actionMode='attack';moveCells=legalMoves(state,u.id);updatePreview();updateHUD();tone(525);return}if(!selected)return;const actor=chosen();if(!actor||!isMine(actor))return;const object=tileAt(hovered.x,hovered.y)?.object;const type:Command['type']=actionMode==='ability'?'ability':u&&u.team!==actor.team||actionMode==='attack'&&(object==='cover'||object==='fragile'&&shiftHeld)?'attack':'move';commit({type,unitId:actor.id,x:hovered.x,y:hovered.y} as Command)}
function bindTabletButtons(){
  const battle=document.querySelector('.battle');if(!battle||replayMode)return;
  battle.insertAdjacentHTML('beforeend',`<div class="tablet-controls" aria-label="Сенсорное управление"><div class="tablet-hint" id="tablet-hint">Касание — выбор и прогноз · проведите пальцем — камера · два пальца — масштаб</div><div id="tablet-cell" class="tablet-cell"></div><div class="tablet-actions"><button id="touch-attack" class="btn ghost" disabled>⚔ Атака</button><button id="touch-ability" class="btn ghost" disabled>✦ Приём</button></div><div class="tablet-tools"><button id="touch-confirm" class="btn primary" disabled>Подтвердить приказ</button><button id="touch-clear" class="btn ghost">Снять выбор</button><button id="touch-ground" class="btn ghost" aria-pressed="false">Клетки</button><button id="touch-bridge" class="btn ghost" aria-pressed="false">Удар по мосту</button><button id="touch-heights" class="btn ghost" aria-pressed="${touchHeights}">Высоты</button></div></div>`);
  document.querySelector('#touch-confirm')?.addEventListener('click',()=>{const order=touchOrder;if(!order||!playerCanAct()||state!==order.state)return;touchOrder=null;commit(order.command);updateHUD()});
  document.querySelector('#touch-clear')?.addEventListener('click',()=>{touchOrder=null;selected=null;hovered=null;preview=null;moveCells=[];updateHUD()});
  document.querySelector('#touch-ground')?.addEventListener('click',()=>{touchGround=!touchGround;touchOrder=null;hovered=null;preview=null;updateHUD()});
  document.querySelector('#touch-bridge')?.addEventListener('click',()=>{touchBridge=!touchBridge;shiftHeld=touchBridge;actionMode='attack';touchOrder=null;hovered=null;preview=null;updateHUD()});
  document.querySelector('#touch-heights')?.addEventListener('click',()=>{touchHeights=!touchHeights;updateHUD()});
  for(const mode of ['attack','ability'] as const)document.querySelector('#touch-'+mode)?.addEventListener('click',()=>{if(!playerCanAct())return;touchOrder=null;actionMode=mode;hovered=null;preview=null;updateHUD();tone(480)});
}
function updateTabletButtons(){
  const actor=chosen();
  const names:Record<Archetype,string>={sword:'Толчок / стража',archer:'Прицельный выстрел',spear:'Натиск',shield:'Стража',scout:'Рывок',engineer:'Капкан / подрыв'};
  for(const mode of ['attack','ability'] as const){const button=document.querySelector<HTMLButtonElement>('#touch-'+mode);if(!button)continue;button.disabled=!actor||!actor.alive||!isMine(actor)||actor.acted||!playerCanAct();button.classList.toggle('active',actionMode===mode);button.setAttribute('aria-pressed',String(actionMode===mode));if(mode==='ability')button.textContent=actor?'✦ Приём · '+(actor.archetype==='engineer'&&actor.variant==='mason'?'Укрепление':names[actor.archetype]):'✦ Приём';}
  const confirm=document.querySelector<HTMLButtonElement>('#touch-confirm');if(confirm){confirm.disabled=!touchOrder||!playerCanAct();confirm.textContent=touchOrder?.command.type==='move'?'Подтвердить шаг':touchOrder?.command.type==='ability'?'Подтвердить приём':touchOrder?'Подтвердить атаку':'Подтвердить приказ'}
  for(const [id,active]of [['touch-ground',touchGround],['touch-bridge',touchBridge],['touch-heights',touchHeights]] as const){const button=document.querySelector('#'+id);button?.setAttribute('aria-pressed',String(active));button?.classList.toggle('active',active)}
  const hint=document.querySelector('#tablet-hint');if(hint)hint.textContent=touchOrder?'Проверьте прогноз и подтвердите приказ кнопкой.':touchGround?'Клетки: касание выбирает землю за фигурой.':touchBridge?'Удар по мосту: выберите бойца, коснитесь моста и проверьте прогноз.':'Касание — выбор и прогноз · проведите пальцем — камера · два пальца — масштаб';
  const details=document.querySelector('#tablet-cell'),tile=hovered?tileAt(hovered.x,hovered.y):null,u=chosen();
  if(details)details.textContent=[u?`${NAMES[u.archetype]} ${u.hp}♥`:'',tile?`${tile.x+1}:${tile.y+1} · высота ${tile.h} · ${TERRAIN[tile.terrain]}${tile.object?' · '+objectName(tile.object):''}${tileHazardDamage(tile)?' · урон '+tileHazardDamage(tile):''}`:''].filter(Boolean).join(' | ');
}
function tabletTap(point:{x:number;y:number}){
  if(!state||modal||replayMode)return;touchOrder=null;shiftHeld=touchBridge;hovered=pick(point.x,point.y,touchGround);
  if(!hovered){preview=null;updateHUD();return}
  const target=unitAt(hovered.x,hovered.y),actor=chosen();
  const selfAbility=actor?.id===target?.id&&actionMode==='ability';
  if(target&&(!actor||target.team===state.team&&!selfAbility&&!reinforcing(actor,tileAt(hovered.x,hovered.y)))){
    selected=target.id;actionMode='attack';moveCells=isMine(target)?legalMoves(state,target.id):[];preview=null;updateHUD();tone(525);return;
  }
  updatePreview();if(playerCanAct()&&preview?.valid&&actor&&['move','attack','ability'].includes(preview.type))touchOrder={command:{type:preview.type,unitId:actor.id,x:hovered.x,y:hovered.y} as Command,state,mode:actionMode};
  updateHUD();
}
function zoomBoard(factor:number,center:{x:number;y:number}){const old=camera.zoom;camera.zoom=Math.max(.52,Math.min(2.4,old*factor));const ratio=camera.zoom/old;camera.x=center.x-(center.x-camera.x-canvas.clientWidth/2)*ratio-canvas.clientWidth/2;camera.y=center.y-(center.y-camera.y-canvas.clientHeight*.48)*ratio-canvas.clientHeight*.48}
function tileSize(){const m=state?.map.width??20;return Math.min(62,Math.max(39,canvas.clientWidth/(m*1.7)))*camera.zoom}
function project(x:number,y:number,h=0){const s=tileSize(),w=state?.map.width??20,height=state?.map.height??20;return{x:canvas.clientWidth/2+camera.x+(x-y-(w-height)/2)*s*.5,y:canvas.clientHeight*.48+camera.y+(x+y-(w+height)/2)*s*.24-h*s*.21}}
function visualPosition(u:Unit){const m=motions.get(u.id);if(reduceMotion||!m)return project(u.x,u.y,tileAt(u.x,u.y)?.h??0);const raw=(performance.now()-m.at)/m.duration;if(raw>=1){motions.delete(u.id);return project(u.x,u.y,tileAt(u.x,u.y)?.h??0)}const point=sampleMotion(m),p=project(point.x,point.y,point.h);p.y-=Math.sin(Math.PI*raw)*tileSize()*.055;return p}
function drawUnitBase(p:{x:number;y:number},s:number,u:Unit){ctx.save();const color=u.team==='blue'?'#79dacd':'#ef8d78';ctx.shadowColor=color;ctx.shadowBlur=u.id===selected?s*.26:s*.1;ctx.fillStyle=u.team==='blue'?'#245f5c':'#743e3b';ctx.strokeStyle=color;ctx.lineWidth=u.id===selected?3:2;ctx.beginPath();ctx.ellipse(p.x,p.y+s*.08,s*.31,s*.135,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function pick(mx:number,my:number,groundOnly=false){if(!state)return null;const s=tileSize();for(const u of [...state.units].filter(v=>v.alive&&!groundOnly).sort((a,b)=>a.x+a.y-b.x-b.y).reverse()){const p=project(u.x,u.y,tileAt(u.x,u.y)?.h??0);if(Math.abs(mx-p.x)<s*.28&&my>p.y-s*.7&&my<p.y+s*.22)return{x:u.x,y:u.y}}let found:null|{x:number;y:number}=null,best=Infinity;for(const t of state.map.tiles){const p=project(t.x,t.y,t.h);const dx=Math.abs(mx-p.x)/(s*.5),dy=Math.abs(my-p.y)/(s*.25);if(dx+dy<=1.05&&(!groundOnly||dx+dy<best)){found={x:t.x,y:t.y};best=dx+dy}}return found}
function polygon(points:{x:number;y:number}[],fill:string,stroke?:string,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
function diamond(p:{x:number;y:number},s:number,fill:string,stroke?:string,width=1){polygon([{x:p.x,y:p.y-s*.25},{x:p.x+s*.5,y:p.y},{x:p.x,y:p.y+s*.25},{x:p.x-s*.5,y:p.y}],fill,stroke,width)}
function hash(x:number,y:number){let n=(x*374761393+y*668265263+20260930)|0;n=(n^(n>>13))*1274126177;return((n^(n>>16))>>>0)/4294967295}
function frame(){if(screen!=='battle'||!state||!canvas.isConnected)return;const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#34463c');g.addColorStop(1,'#151f1a');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);drawBoard();drawOverlay();drawStandingObjects();drawHeightLabels();drawUnits();drawHazardMarkers();drawDamageNumbers();raf=requestAnimationFrame(frame)}
function drawHeightLabels(){if(!state)return;const s=tileSize();ctx.save();ctx.font=`bold ${Math.max(11,s*.18)}px Manrope, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';for(const t of state.map.tiles){if(t.h===0)continue;const nearHover=hovered&&Math.abs(t.x-hovered.x)+Math.abs(t.y-hovered.y)<=1;const relevant=showAllHeights||touchHeights||highContrast||nearHover||unitAt(t.x,t.y)||t.terrain==='stairs'||moveCells.some(c=>c.x===t.x&&c.y===t.y);if(!relevant)continue;const p=project(t.x,t.y,t.h),x=p.x-s*.32,y=p.y+s*.065,r=Math.max(7,s*.105);ctx.fillStyle='#1b2b23';ctx.strokeStyle='#d7c799';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(x-r,y-r,r*2,r*2,3);ctx.fill();ctx.stroke();ctx.fillStyle='#fff1c9';ctx.fillText(String(t.h),x,y)}ctx.restore()}
function drawDamageNumbers(){const now=performance.now(),s=tileSize();for(let i=damageNumbers.length-1;i>=0;i--){const d=damageNumbers[i],elapsed=now-d.at,life=1700;if(elapsed<0)continue;if(elapsed>=life){damageNumbers.splice(i,1);continue}const t=elapsed/life,p=project(d.x,d.y,d.h);ctx.save();ctx.globalAlpha=Math.min(1,(1-t)*2.4);ctx.font=`900 ${Math.max(22,s*.4)}px Manrope, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=Math.max(3,s*.07);ctx.strokeStyle='#14231b';ctx.fillStyle=d.fatal?'#ffe1a1':d.team==='blue'?'#f4aaa0':'#b9eee0';const y=p.y-s*(.83+.55*(reduceMotion?0:t));ctx.strokeText(`−${d.amount}`,p.x,y);ctx.fillText(`−${d.amount}`,p.x,y);ctx.font=`bold ${Math.max(12,Math.min(15,s*.19))}px Manrope, sans-serif`;ctx.lineWidth=4;ctx.fillStyle='#fff0c8';ctx.strokeText(d.source,p.x,y+22);ctx.fillText(d.source,p.x,y+22);if(d.fatal){ctx.font='bold 10px Manrope, sans-serif';ctx.fillStyle='#ffe5ae';ctx.strokeText('ПОРАЖЁН',p.x,y+38);ctx.fillText('ПОРАЖЁН',p.x,y+38)}ctx.restore()}}
function drawBoard(){if(!state)return;const s=tileSize();const tiles=[...state.map.tiles].sort((a,b)=>(a.x+a.y)-(b.x+b.y));for(const t of tiles){const p=project(t.x,t.y,t.h),depth=4+t.h*s*.18;const left={x:p.x-s*.5,y:p.y},right={x:p.x+s*.5,y:p.y},bottom={x:p.x,y:p.y+s*.25};polygon([left,bottom,{x:bottom.x,y:bottom.y+depth},{x:left.x,y:left.y+depth}],t.terrain==='water'?'#263e42':'#344232','#14211b66');polygon([right,bottom,{x:bottom.x,y:bottom.y+depth},{x:right.x,y:right.y+depth}],t.terrain==='water'?'#2b5051':'#28382c','#14211b66');
let c=t.terrain==='water'?'#386e88':t.terrain==='stone'?'#838b7c':t.terrain==='bridge'?'#a18660':t.terrain==='stairs'?'#a39b81':t.terrain==='rubble'?'#706e5b':(hash(t.x,t.y)>.5?'#768d67':'#6e865f');if(t.h>=2&&t.terrain==='grass')c=hash(t.x,t.y)>.5?'#8a9a71':'#81936e';diamond(p,s,c,'#192b244f',1);
if(t.terrain==='water'){ctx.save();ctx.strokeStyle='#9cd4df88';ctx.lineWidth=1;const phase=reduceMotion?0:Math.sin(performance.now()/1100+t.x*.8+t.y*.4)*s*.02;for(let i=-1;i<=1;i++){ctx.beginPath();const x=p.x+i*s*.09,y=p.y+i*s*.07;ctx.moveTo(x-s*.13,y+phase);ctx.quadraticCurveTo(x-s*.04,y+phase-s*.035,x+s*.1,y+phase);ctx.stroke()}ctx.restore()}
const hv=hash(t.x+24,t.y);if(t.terrain==='grass'&&hv>.22){ctx.strokeStyle=hv>.7?'#c3b68988':'#344f3577';ctx.lineWidth=1;for(let i=0;i<3;i++){const xx=p.x+(hash(t.x+i,t.y+9)-.5)*s*.48,yy=p.y+(hash(t.x,t.y+i+17)-.5)*s*.16;ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(xx+(i-1)*2,yy-3-hv*3);ctx.stroke()}}if(t.terrain==='stone'||t.terrain==='rubble'){ctx.strokeStyle='#52625988';ctx.beginPath();ctx.moveTo(p.x-s*.22,p.y+s*.05);ctx.lineTo(p.x-s*.09,p.y-s*.04);ctx.lineTo(p.x+s*.06,p.y+s*.06);ctx.stroke()}if(t.terrain==='stairs'){ctx.strokeStyle='#504f4388';for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(p.x-s*.2,p.y+i*s*.06);ctx.lineTo(p.x+s*.2,p.y+i*s*.06);ctx.stroke()}}if(t.terrain==='bridge'){ctx.strokeStyle='#4b4130aa';for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(p.x+i*s*.13-s*.16,p.y-s*.12);ctx.lineTo(p.x+i*s*.13+s*.16,p.y+s*.12);ctx.stroke()}}
const groundSprite=terrainSprite(t);if(groundSprite){drawPropSprite(ctx,groundSprite,p,s);diamond(p,s,'#00000000','#192b2455',1)}
if(t.object==='objective'&&state.objective.kind==='control')drawObjectiveAura(t,p,s);
}}
function drawStandingObjects(){if(!state)return;const s=tileSize();for(const t of [...state.map.tiles].sort((a,b)=>a.x+a.y-b.x-b.y)){if(t.object&&(t.object!=='objective'||state.objective.kind==='control'))drawStyledObject(t,project(t.x,t.y,t.h),s)}}
function drawHazardMarkers(){if(!state)return;const s=tileSize();ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`bold ${Math.max(10,s*.16)}px Manrope, sans-serif`;for(const t of state.map.tiles){if(t.object!=='trap'&&t.object!=='brazier')continue;const p=project(t.x,t.y,t.h),x=p.x+s*.34,y=p.y-s*.035;ctx.fillStyle='#432e20';ctx.strokeStyle='#f0b175';ctx.lineWidth=1.5;ctx.beginPath();ctx.roundRect(x-10,y-7,20,14,3);ctx.fill();ctx.stroke();ctx.fillStyle='#ffe1ac';ctx.fillText(`−${tileHazardDamage(t)}`,x,y)}ctx.restore()}
function drawStyledObject(t:Tile,p:{x:number;y:number},s:number){
 const object=t.object;if(!object)return;
 if(object==='fragile'){drawObject(t,p,s);ctx.fillStyle='#17251d';ctx.fillRect(p.x-s*.18,p.y+s*.16,s*.36,3);ctx.fillStyle='#d6c18b';ctx.fillRect(p.x-s*.18,p.y+s*.16,s*.36*Math.min(1,(t.hp??2)/4),3);return}
 const sprite=object==='cover'?'rock':object==='trap'?'trap':object==='objective'?'banner':(t.x+t.y)%2?'torch':'brazier';
 if(object==='brazier'||object==='trap'){
   ctx.save();ctx.strokeStyle=object==='trap'?'#ebba87':'#f3a16d';ctx.lineWidth=1.5;ctx.setLineDash([3,3]);
   diamond(p,s*.69,object==='trap'?'#a3452920':'#cb6d2720',ctx.strokeStyle,1.5);ctx.restore();
 }
 const opacity=object==='objective'&&unitAt(t.x,t.y)? .45:1;
 if(!drawPropSprite(ctx,sprite,p,s,opacity)){drawObject(t,p,s);return}
 if(object==='cover'){
   ctx.save();ctx.fillStyle='#17251d';ctx.fillRect(p.x-s*.18,p.y+s*.16,s*.36,3);
   ctx.fillStyle='#d6c18b';ctx.fillRect(p.x-s*.18,p.y+s*.16,s*.36*Math.min(1,(t.hp??2)/4),3);ctx.restore();
 }
 if(object==='brazier'){
   ctx.save();const pulse=reduceMotion?.7:.6+.15*Math.sin(performance.now()/180+t.x*3+t.y);
   ctx.globalAlpha=pulse;ctx.fillStyle='#ffb45a33';ctx.beginPath();ctx.ellipse(p.x,p.y+s*.015,s*.23,s*.12,0,0,Math.PI*2);ctx.fill();
   if(!reduceMotion){for(let i=0;i<3;i++){const life=(performance.now()/1100+i*.31+t.x*.17)%1;ctx.globalAlpha=(1-life)*.7;ctx.fillStyle='#ffc978';ctx.fillRect(p.x+Math.sin(life*5+i)*s*.055,p.y-s*(.26+life*.3),1.5,1.5)}}ctx.restore();
 }
}
function drawObjectiveAura(t:Tile,p:{x:number;y:number},s:number){const holder=unitAt(t.x,t.y),team=holder?.team;const color=team==='blue'?'#83e2d0':team==='red'?'#ef947d':'#ffdc8e';const index=state?.objective.points.findIndex(v=>v.x===t.x&&v.y===t.y)??-1;const pulse=.5+.5*Math.sin(performance.now()/520+t.x);ctx.save();ctx.shadowColor=color;ctx.shadowBlur=s*(.15+pulse*.08);diamond(p,s*.74,team==='blue'?'#3b948b99':team==='red'?'#bd645899':'#c9a45e77',color,2.5);ctx.shadowBlur=0;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,s*.09,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.3;ctx.beginPath();ctx.ellipse(p.x,p.y-s*.25,s*.075,s*.25,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#17241d';ctx.font=`bold ${Math.max(10,s*.19)}px Manrope, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';if(index>=0)ctx.fillText(String(index+1),p.x,p.y+s*.13);ctx.restore()}
function drawObject(t:Tile,p:{x:number;y:number},s:number){const o=t.object;if(!o)return;ctx.save();if(o==='objective'){const pulse=.5+.5*Math.sin(performance.now()/470);ctx.fillStyle=`rgba(241,191,102,${.12+pulse*.13})`;ctx.beginPath();ctx.ellipse(p.x,p.y-s*.09,s*.39,s*.2,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f2cc7f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y-s*.17);ctx.lineTo(p.x,p.y-s*.85);ctx.stroke();polygon([{x:p.x,y:p.y-s*.82},{x:p.x+s*.28,y:p.y-s*.72},{x:p.x,y:p.y-s*.59}],'#d7ad5c','#f1d695');ctx.fillStyle='#ffe3a2';ctx.beginPath();ctx.arc(p.x,p.y-s*.16,s*.08,0,7);ctx.fill()}else if(o==='cover'){ctx.fillStyle='#5b6259';ctx.fillRect(p.x-s*.21,p.y-s*.22,s*.42,s*.2);ctx.fillStyle='#9b9b83';ctx.fillRect(p.x-s*.21,p.y-s*.26,s*.42,s*.09)}else if(o==='brazier'){ctx.fillStyle='#4c4b3f';ctx.fillRect(p.x-s*.08,p.y-s*.2,s*.16,s*.2);ctx.fillStyle='#ffca76';ctx.beginPath();ctx.arc(p.x,p.y-s*.29,s*.09,0,7);ctx.fill();ctx.fillStyle='#f77e49';ctx.beginPath();ctx.arc(p.x,p.y-s*.33,s*.045,0,7);ctx.fill()}else if(o==='trap'){ctx.strokeStyle='#bd8f69';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,s*.15,0,7);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x-s*.12,p.y-s*.06);ctx.lineTo(p.x+s*.1,p.y+s*.07);ctx.stroke()}else if(o==='fragile'){ctx.strokeStyle='#f0bd7b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x-s*.15,p.y-s*.07);ctx.lineTo(p.x+s*.08,p.y+s*.08);ctx.lineTo(p.x+s*.2,p.y-s*.02);ctx.stroke()}ctx.restore()}
function drawUnits(){
if(!state)return;if(!spriteAssetsReady()){drawLegacyUnits();return}
const s=tileSize();for(const u of [...state.units].filter(v=>v.alive||spriteDeathVisible(v.id)).sort((a,b)=>(a.x+a.y)-(b.x+b.y))){
 const p=visualPosition(u),r=s*.25;
 if(u.alive){ctx.fillStyle='#0a15129e';ctx.beginPath();ctx.ellipse(p.x,p.y+s*.09,r*1.15,r*.4,0,0,7);ctx.fill();drawUnitBase(p,s,u);
 if(u.id===selected||hovered?.x===u.x&&hovered?.y===u.y){ctx.strokeStyle=u.id===selected?'#f4d484':'#ffffffbb';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+s*.04,r*1.43,r*.53,0,0,7);ctx.stroke()}}
 drawFighterSprite(ctx,u,p,s,motions.has(u.id),animationSpeed,reduceMotion);
 if(!u.alive)continue;
 if(u.commander){ctx.fillStyle='#f5d991';ctx.strokeStyle='#13231b';ctx.lineWidth=3;ctx.font='bold '+Math.max(14,s*.23)+'px Georgia';ctx.textAlign='center';ctx.strokeText('♛',p.x,p.y-s*.94);ctx.fillText('♛',p.x,p.y-s*.94)}
 ctx.fillStyle='#1a241e';ctx.fillRect(p.x-r,p.y+s*.19,r*2,4);ctx.fillStyle=u.team==='blue'?'#a0d4bd':'#eaa18c';ctx.fillRect(p.x-r,p.y+s*.19,r*2*(u.hp/u.maxHp),4);
}}
function drawLegacyUnits(){if(!state)return;const s=tileSize();for(const u of [...state.units].filter(x=>x.alive).sort((a,b)=>(a.x+a.y)-(b.x+b.y))){const p=visualPosition(u),r=s*.25,baseY=p.y-s*.09;ctx.fillStyle='#0a15129e';ctx.beginPath();ctx.ellipse(p.x,p.y+s*.09,r*1.15,r*.4,0,0,7);ctx.fill();drawUnitBase(p,s,u);ctx.save();ctx.translate(p.x,baseY);if(u.id===selected||hovered?.x===u.x&&hovered?.y===u.y){ctx.strokeStyle=u.id===selected?'#f4d484':'#ffffffbb';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,s*.14,r*1.43,r*.53,0,0,7);ctx.stroke()}const color=u.team==='blue'?'#87c6b6':'#e58b74',dark=u.team==='blue'?'#285c5b':'#813b3b';ctx.fillStyle=dark;ctx.beginPath();ctx.moveTo(-r*.8,s*.04);ctx.lineTo(r*.8,s*.04);ctx.lineTo(r*.65,-r*1.15);ctx.lineTo(-r*.7,-r*1.15);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-r*.68,-r*.2);ctx.lineTo(r*.72,-r*.2);ctx.lineTo(r*.48,-r*1.38);ctx.lineTo(-r*.43,-r*1.38);ctx.fill();ctx.fillStyle='#efddbd';ctx.beginPath();ctx.arc(0,-r*1.5,r*.36,0,7);ctx.fill();ctx.fillStyle=dark;ctx.beginPath();ctx.arc(0,-r*1.74,r*.39,Math.PI,Math.PI*2);ctx.lineTo(r*.4,-r*1.62);ctx.lineTo(-r*.4,-r*1.62);ctx.fill();ctx.strokeStyle='#f4e3bb';ctx.lineWidth=Math.max(2,s*.047);ctx.lineCap='round';if(u.archetype==='archer'){ctx.beginPath();ctx.arc(r*.53,-r*.82,r*.63,-1.45,1.45);ctx.stroke();ctx.strokeStyle='#5d352b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(r*.59,-r*1.43);ctx.lineTo(r*.59,-r*.21);ctx.stroke()}if(u.archetype==='sword'){ctx.beginPath();ctx.moveTo(r*.6,-r*.3);ctx.lineTo(r*1.1,-r*1.75);ctx.stroke();ctx.beginPath();ctx.moveTo(r*.7,-r*.75);ctx.lineTo(r*1.3,-r*.55);ctx.stroke()}if(u.archetype==='spear'){ctx.beginPath();ctx.moveTo(r*.63,r*.12);ctx.lineTo(r*1.2,-r*2.3);ctx.stroke();polygon([{x:r*1.2,y:-r*2.55},{x:r*1.02,y:-r*2.17},{x:r*1.3,y:-r*2.2}],'#dce3d4')}if(u.archetype==='shield'){polygon([{x:r*.35,y:-r*.7},{x:r*1.2,y:-r*.7},{x:r*1.15,y:r*.25},{x:r*.75,y:r*.55},{x:r*.35,y:r*.25}],dark,'#e5cf9e',2)}if(u.archetype==='scout'){ctx.beginPath();ctx.moveTo(r*.4,-r*.5);ctx.lineTo(r*1.1,-r*1.25);ctx.stroke();ctx.fillStyle='#a6d1a1';ctx.beginPath();ctx.moveTo(-r*.4,-r*1.7);ctx.lineTo(0,-r*2.2);ctx.lineTo(r*.4,-r*1.7);ctx.fill()}if(u.archetype==='engineer'){ctx.beginPath();ctx.moveTo(r*.55,0);ctx.lineTo(r*1.2,-r*1.65);ctx.stroke();ctx.fillStyle='#c4ac79';ctx.fillRect(r*.9,-r*1.8,r*.7,r*.24)}if(u.commander){ctx.fillStyle='#f5d991';ctx.font=`${r*.7}px Georgia`;ctx.textAlign='center';ctx.fillText('♛',0,-r*2.16)}if(u.acted){ctx.fillStyle='#07120aa0';ctx.beginPath();ctx.arc(0,-r*.7,r*1.4,0,7);ctx.fill()}ctx.restore();ctx.fillStyle='#1a241e';ctx.fillRect(p.x-r,p.y+s*.19,r*2,3);ctx.fillStyle=u.team==='blue'?'#a0d4bd':'#eaa18c';ctx.fillRect(p.x-r,p.y+s*.19,r*2*(u.hp/u.maxHp),3)}}
function drawScenarioMarkers(s:number){if(!state)return;ctx.save();for(const p of state.objective.exits??[]){const q=project(p.x,p.y,tileAt(p.x,p.y)?.h??0);diamond(q,s*.88,'#4edfa240','#b0ffce',3);ctx.fillStyle='#d2ffe2';ctx.textAlign='center';ctx.font=`bold ${Math.max(13,s*.28)}px sans-serif`;ctx.fillText('↗',q.x,q.y+s*.08)}for(const p of state.objective.defendPoints??[]){const q=project(p.x,p.y,tileAt(p.x,p.y)?.h??0);diamond(q,s*.88,'#eac16b40','#ffda8e',3)}for(const u of state.units.filter(u=>u.alive&&state!.objective.protectedIds?.includes(u.id))){const q=visualPosition(u);ctx.fillStyle='#ffe0a1';ctx.textAlign='center';ctx.font=`bold ${Math.max(13,s*.23)}px sans-serif`;ctx.fillText('◇',q.x,q.y-s*.95)}ctx.restore()}
function drawOverlay(){if(!state)return;const s=tileSize(),u=chosen();drawScenarioMarkers(s);if(u?.alive&&isMine(u)&&!u.moved){for(const c of moveCells){const p=project(c.x,c.y,tileAt(c.x,c.y)?.h??0);const danger=tileAt(c.x,c.y)?.object==='trap'||tileAt(c.x,c.y)?.object==='brazier';diamond(p,s,danger?'#bb6b2b45':c.threatened?'#e9a15e55':'#78d5c044',danger?'#ffc38a':c.threatened?'#f4b978':'#87dfcb88',danger?2:1)}}if(u?.alive&&isMine(u)&&!u.acted){for(const enemy of state.units.filter(v=>v.alive&&v.team!==u.team)){let p:Preview;try{p=previewAction(state,{type:actionMode,unitId:u.id,x:enemy.x,y:enemy.y})}catch{continue}if(p.valid){diamond(project(enemy.x,enemy.y,tileAt(enemy.x,enemy.y)?.h??0),s,'#e76d5c55','#ffad8e',2)}}}
if(u&&isMine(u)&&!u.acted&&actionMode==='ability'&&['sword','shield'].includes(u.archetype))diamond(project(u.x,u.y,tileAt(u.x,u.y)?.h??0),s,'#e3bf7144','#ffe2a1',3);
if(state.mode==='ai'&&state.team==='blue'){const forecast={...state,team:'red' as const,units:state.units.map(v=>v.team==='red'?{...v,moved:false,acted:false}:v)};for(const e of forecast.units.filter(v=>v.alive&&v.team==='red')){const targets=forecast.units.filter(v=>v.alive&&v.team==='blue').map(v=>({v,p:previewAction(forecast,{type:'attack',unitId:e.id,x:v.x,y:v.y})})).filter(q=>q.p.valid).sort((a,b)=>(b.p.damage??0)-(a.p.damage??0));if(targets[0]){const a=project(e.x,e.y,tileAt(e.x,e.y)?.h??0),b=project(targets[0].v.x,targets[0].v.y,tileAt(targets[0].v.x,targets[0].v.y)?.h??0);ctx.strokeStyle='#e97e6780';ctx.setLineDash([5,5]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y-s*.35);ctx.lineTo(b.x,b.y-s*.35);ctx.stroke();ctx.setLineDash([])}}}
if(hovered){const p=project(hovered.x,hovered.y,tileAt(hovered.x,hovered.y)?.h??0);const rejected=preview&&!preview.valid;diamond(p,s,rejected?'#bb49351c':'#ffffff10',rejected?'#f19880':'#fff3cb',2);if(rejected){ctx.strokeStyle='#f19880';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x-s*.10,p.y-s*.06);ctx.lineTo(p.x+s*.10,p.y+s*.06);ctx.moveTo(p.x+s*.10,p.y-s*.06);ctx.lineTo(p.x-s*.10,p.y+s*.06);ctx.stroke()}if(preview?.path){ctx.strokeStyle='#e8e9bd';ctx.lineWidth=3;ctx.setLineDash([4,3]);ctx.beginPath();for(const [i,c] of preview.path.entries()){const q=project(c.x,c.y,tileAt(c.x,c.y)?.h??0);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)}ctx.stroke();ctx.setLineDash([])}if(preview?.valid&&preview.type!=='move'&&u){const a=project(u.x,u.y,tileAt(u.x,u.y)?.h??0);ctx.strokeStyle='#ffdc9c';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.beginPath();ctx.moveTo(a.x,a.y-s*.34);ctx.lineTo(p.x,p.y-s*.34);ctx.stroke();ctx.setLineDash([]);if(preview.push){const q=project(preview.push.x,preview.push.y,tileAt(preview.push.x,preview.push.y)?.h??0);ctx.strokeStyle='#ff9877';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}}
if(activePulse){const elapsed=(performance.now()-activePulse.at)*animationSpeed;if(elapsed<550&&tileAt(activePulse.x,activePulse.y)?.terrain!=='water'){const p=project(activePulse.x,activePulse.y,tileAt(activePulse.x,activePulse.y)?.h??0);ctx.strokeStyle=activePulse.kind==='move'?`rgba(134,222,191,${1-elapsed/550})`:`rgba(255,184,108,${1-elapsed/550})`;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,s*(.12+elapsed/1300),s*(.06+elapsed/2600),0,0,7);ctx.stroke()}else activePulse=null}}
document.addEventListener('keydown',e=>{if(screen==='battle'&&e.code==='KeyH')showAllHeights=true});
document.addEventListener('keyup',e=>{if(e.code==='KeyH')showAllHeights=false});
window.addEventListener('blur',()=>{showAllHeights=false});
document.addEventListener('keydown',e=>{if(modal&&screen!=='battle'){if(e.key==='Escape'){modal=null;render()}return}if(screen==='story'){if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLSelectElement)return;if(e.key==='Escape'){e.preventDefault();if(storyLog){storyLog=false;renderStory()}else setScreen('menu')}else if(e.key==='Enter'||e.key===' '){e.preventDefault();advanceStory()}else if(e.key==='ArrowLeft'&&!storyLog){e.preventDefault();saveStory(stepStory(storyProgress(),-1));renderStory()}return}if(screen==='howto'&&e.key==='Escape'){setScreen('menu');return}if(screen!=='battle')return;if(e.key==='Escape'){modal=modal?null:'pause';renderBattle()}if(modal)return;if(e.target instanceof HTMLButtonElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLInputElement)return;if(e.key.toLowerCase()==='q'&&state&&playerCanAct()){e.preventDefault();const list=state.units.filter(u=>u.alive&&u.team===state!.team);const i=list.findIndex(u=>u.id===selected);selected=list[(i+1)%list.length]?.id??null;moveCells=selected?legalMoves(state,selected):[];actionMode='attack';updatePreview();updateHUD()}if(e.key==='Enter')endPlayerTurn();if(e.key==='u'||e.key==='U')doUndo();if(e.key==='1'){actionMode='attack';updatePreview();updateHUD()}if(e.key==='2'){actionMode='ability';updatePreview();updateHUD()}if(e.key==='ArrowLeft')camera.x+=35;if(e.key==='ArrowRight')camera.x-=35;if(e.key==='ArrowUp')camera.y+=35;if(e.key==='ArrowDown')camera.y-=35});
render();


